import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import nbt from 'prismarine-nbt';
import {compileSpec,hash} from '../../src/generation/compiler.mjs';import {designExamples,designNode as n,designPalette} from '../../src/generation/design-examples.mjs';
import {resolveState,validateState,parseState,transformState} from '../../src/generation/block-states.mjs';import {exportCompiled} from '../../src/generation/export.mjs';import {readNativeBundle} from '../../src/generation/bundle.mjs';import {mergeInterior} from '../../bridge/layered-generation.mjs';
const compile=s=>compileSpec(s,{navigationPolicy:'review'});
function specimen(){return {schemaVersion:2,id:'special-block-test',seed:1,units:'block',bounds:{width:12,height:8,length:12},palette:designPalette(),design:{style:'test',concept:'test',silhouette:'test',paletteIntent:'test',features:[]},nodes:[n('floor','box',[0,0,0],[12,1,12],'floor'),n('door','door',[2,1,2],[1,2,1],'door',{facing:'east',hinge:'right',open:false}),n('slab','box',[4,1,2],[1,1,1],'slab',{type:'top'}),n('trap','box',[6,1,2],[1,1,1],'trapdoor',{facing:'west',half:'top',open:true}),n('stair','box',[8,1,2],[1,1,1],'stairs',{facing:'south',half:'top',shape:'outer_left'})],groups:[],instances:[],constraints:{interior:false,walkable:false,passages:[]}};}
test('v2 design studies compile with distinct compositions and >6 material roles',()=>{for(const s of designExamples()){const c=compile(s);assert.ok(c.manifest.setCount>1000);assert.ok(Object.keys(s.palette).length>6);assert.deepEqual(c.manifest.design,s.design);assert.equal(c.manifest.quality.requiresAcknowledgement,true);}});
test('special state matrix rejects illegal properties and wet/powered blocks',()=>{
 for(const facing of ['north','south','east','west'])for(const half of ['bottom','top'])for(const open of [true,false])assert.doesNotThrow(()=>validateState(resolveState('oak_trapdoor',{facing,half,open})));
 for(const type of ['bottom','top','double'])assert.match(resolveState('quartz_slab',{type}),new RegExp('type='+type));
 for(const material of ['stone','oak_stairs','oak_door'])assert.throws(()=>resolveState(material,{waterlogged:true}));assert.throws(()=>resolveState('stone',{facing:'east'}));assert.throws(()=>resolveState('oak_door',{half:'bottom'}));assert.throws(()=>validateState('minecraft:oak_door[facing=north,half=lower,hinge=left,open=false,powered=true]'));
});
test('paired doors are mandatory; missing support allows warned preview but fails strict compilation',()=>{const c=compile(specimen()),at=(x,y,z)=>c.manifest.palette[c.cells[x+z*12+y*144]];assert.match(at(2,1,2),/half=lower/);assert.match(at(2,2,2),/half=upper/);assert.equal(c.manifest.quality.navigation,'unverified');const s=specimen();s.nodes.push(n('bad','keep',[2,2,2],[1,1,1]));assert.throws(()=>compile(s),/Door/);s.nodes.pop();s.nodes.push(n('bad','clear',[2,0,2],[1,1,1]));assert.throws(()=>compileSpec(s),/Door requires/);const preview=compile(s);assert.ok(preview.manifest.quality.issues.some(i=>i.code==='door-support-unverified'));assert.equal(preview.cells[2+2*12],1);});
test('approved literal materials are accepted; aliases take precedence and unknown names fail',()=>{const s=specimen();s.nodes.push(n('leaf','box',[9,1,9],[1,1,1],'leaves'));let c=compile(s);assert.match(c.manifest.palette[c.cells[9+9*12+144]],/leaves/);s.palette.leaves='stone';c=compile(s);assert.equal(c.manifest.palette[c.cells[9+9*12+144]],'minecraft:stone');s.nodes.at(-1).material='command_block';assert.throws(()=>compile(s),/Unknown palette role/);});
test('group rotation and reflection transform coordinates and special states without mutating source',()=>{
 const s=specimen();s.nodes=s.nodes.slice(0,1);s.groups=[{id:'entry',size:[3,3,3],nodes:[n('door','door',[0,0,0],[1,2,1],'door',{facing:'east',hinge:'left',open:true}),n('trim','box',[2,0,0],[1,1,1],'stairs',{facing:'north',half:'top',shape:'inner_left'})]}];s.instances=[{id:'east',group:'entry',origin:[2,1,2],rotation:1,mirror:true,repeat:{count:1,step:[0,0,0]}}];const before=JSON.stringify(s),c=compile(s);assert.equal(JSON.stringify(s),before);assert.ok(c.manifest.palette.some(p=>p.includes('_door[')&&p.includes('facing=north')&&p.includes('hinge=right')));assert.ok(c.manifest.palette.some(p=>p.includes('_stairs[')&&p.includes('facing=east')&&p.includes('shape=inner_right')));
 s.instances[0].origin=[11,1,11];assert.throws(()=>compile(s),/outside bounds/);
});
test('four rotations and two mirrors restore all directional properties',()=>{for(const state of [resolveState('spruce_door',{facing:'east',hinge:'left'}),resolveState('oak_stairs',{facing:'west',shape:'outer_left'}),resolveState('oak_trapdoor',{half:'top',open:true}),resolveState('oak_log',{axis:'x'})]){let rotated=state;for(let i=0;i<4;i++)rotated=transformState(rotated,1,false);assert.deepEqual(parseState(rotated),parseState(state));assert.deepEqual(parseState(transformState(transformState(state,0,true),0,true)),parseState(state));}});
test('native and schematic exports preserve door halves and partial block states exactly',async()=>{const c=compile(specimen()),dir=await fs.mkdtemp(path.join(os.tmpdir(),'voxel-special-'));for(const [name,data] of [['manifest.json',JSON.stringify(c.manifest)],['cells.bin',c.binary],['spec.json',JSON.stringify(c.spec)]])await fs.writeFile(path.join(dir,name),data);assert.equal((await readNativeBundle(dir)).manifest.assetHash,c.manifest.assetHash);const {file}=await exportCompiled(c,dir),{parsed}=await nbt.parse(await fs.readFile(file)),palette=nbt.simplify(parsed).Palette;for(const state of c.manifest.palette.slice(2).filter(s=>/half=upper|type=top|shape=outer_left|open=true/.test(s)))assert.ok(Object.hasOwn(palette,state),state);
 const bad=structuredClone(c.manifest);bad.palette[bad.palette.findIndex(s=>s.includes('half=upper'))]=resolveState('oak_door',{half:'upper'});delete bad.assetHash;bad.assetHash=hash(bad);await fs.writeFile(path.join(dir,'manifest.json'),JSON.stringify(bad));await assert.rejects(readNativeBundle(dir),/Door halves/);
});
test('two-stage v2 preserves design and applies interior after envelope instances',()=>{const a=specimen();a.groups=[{id:'outer',size:[1,1,1],nodes:[n('trim','box',[0,0,0],[1,1,1])]}];a.instances=[{id:'outside',group:'outer',origin:[5,1,5],rotation:0,mirror:false,repeat:{count:1,step:[0,0,0]}}];const b=structuredClone(a);b.nodes=[n('interior','clear',[5,1,5],[1,1,1])];b.groups=[];b.instances=[];b.constraints={interior:true,walkable:true,passages:[]};const merged=mergeInterior(a,b);assert.deepEqual(merged.groups[0],a.groups[0]);assert.deepEqual(merged.design,a.design);assert.equal(compile(merged).cells[5+5*12+144],1);});
