package dev.voxelstudio.selection;

import org.junit.jupiter.api.Test;
import java.util.*;
import static org.junit.jupiter.api.Assertions.*;

final class SelectionCaptureLifetimeTest {
    private final Object original=new Object();private final UUID player=UUID.randomUUID();
    private SelectionReadService.PatchSendBinding binding(String runtime){return new SelectionReadService.PatchSendBinding("00000000-0000-0000-0000-000000000000","a".repeat(64),"b".repeat(64),0,"c".repeat(64),"d".repeat(64),"e".repeat(64),runtime.repeat(64),"f".repeat(64));}
    private SelectionCaptureLifetime<Object> lifetime(){return new SelectionCaptureLifetime<>(original,player,0);}
    @Test void ordinaryCaptureStillExpiresAtFiveMinutes(){var life=lifetime();assertFalse(life.expired(SelectionCaptureLifetime.IDLE_NANOS-1));assertTrue(life.expired(SelectionCaptureLifetime.IDLE_NANOS));assertThrows(IllegalStateException.class,()->life.reserve(original,player,binding("1"),SelectionCaptureLifetime.IDLE_NANOS));}
    @Test void retentionIsNotWriteConsent(){var life=lifetime();assertFalse(life.canAuthorizePlacement());assertFalse(binding("1").canAuthorizePlacement());}
    @Test void onlyOriginalObjectAndPlayerCanReserve(){var life=lifetime();assertThrows(IllegalStateException.class,()->life.reserve(new Object(),player,binding("1"),1));assertThrows(IllegalStateException.class,()->life.reserve(original,UUID.randomUUID(),binding("1"),1));assertEquals(SelectionCaptureLifetime.Phase.IDLE,life.phase());}
    @Test void preparationHasSeparateBoundButDoesNotResetOnReentry(){var life=lifetime();long started=SelectionCaptureLifetime.IDLE_NANOS-10;var pin=binding("1");life.reserve(original,player,pin,started);life.reserve(original,player,pin,started+20);assertFalse(life.expired(started+SelectionCaptureLifetime.DISPATCH_PREPARATION_NANOS-1));assertTrue(life.expired(started+SelectionCaptureLifetime.DISPATCH_PREPARATION_NANOS));assertThrows(IllegalStateException.class,()->life.attempted(original,player,pin,started+SelectionCaptureLifetime.DISPATCH_PREPARATION_NANOS));}
    @Test void differentFrozenTaskOrRuntimeCannotReplaceRetention(){var life=lifetime();life.reserve(original,player,binding("1"),1);assertThrows(IllegalStateException.class,()->life.reserve(original,player,binding("2"),2));assertThrows(IllegalStateException.class,()->life.attempted(original,player,binding("2"),2));}
    @Test void uncertainDispatchedCallHasNoArtificialGenerationDuration(){var life=lifetime();var pin=binding("1");life.reserve(original,player,pin,1);life.beforeDispatch(original,player,pin,2);life.attempted(original,player,pin,3);assertFalse(life.expired(6*60_000_000_000L));assertFalse(life.expired(48*60*60_000_000_000L));assertFalse(life.expired(Long.MAX_VALUE/2));assertEquals(SelectionCaptureLifetime.Phase.POSSIBLY_SENT,life.phase());}
    @Test void networkFailureOrClosedUiAfterDispatchDoesNotReleaseOriginal(){var life=lifetime();var pin=binding("1");life.reserve(original,player,pin,1);life.attempted(original,player,pin,2);life.releaseIfNotDispatched(original,player,pin);assertFalse(life.expired(SelectionCaptureLifetime.IDLE_NANOS*100));assertThrows(IllegalStateException.class,()->life.attempted(original,player,pin,3));assertThrows(IllegalStateException.class,()->life.reserve(original,player,pin,3));}
    @Test void abandonedPreparationKeepsOriginalIdleDeadlineNotNewOne(){var life=lifetime();var pin=binding("1");long started=SelectionCaptureLifetime.IDLE_NANOS-10;life.reserve(original,player,pin,started);life.releaseIfNotDispatched(original,player,pin);assertFalse(life.expired(started+1));assertTrue(life.expired(SelectionCaptureLifetime.IDLE_NANOS));assertThrows(IllegalStateException.class,()->life.reserve(original,player,pin,started+1));}
    @Test void revokedEnvironmentSelectionWorldOrHandoffCannotBeResurrected(){for(boolean sent:new boolean[]{false,true}){var life=lifetime();var pin=binding("1");life.reserve(original,player,pin,1);if(sent)life.attempted(original,player,pin,2);life.revoke();assertTrue(life.expired(3));assertThrows(IllegalStateException.class,()->life.reserve(original,player,pin,3));assertThrows(IllegalStateException.class,()->life.attempted(original,player,pin,3));life.releaseIfNotDispatched(original,player,pin);assertEquals(SelectionCaptureLifetime.Phase.REVOKED,life.phase());}}
    @Test void malformedOrMissingPinsDoNotMintRetention(){assertThrows(IllegalArgumentException.class,()->binding("wrong"));assertThrows(IllegalArgumentException.class,()->new SelectionReadService.PatchSendBinding("invalid","a".repeat(64),"b".repeat(64),0,"c".repeat(64),"d".repeat(64),"e".repeat(64),"1".repeat(64),"f".repeat(64)));assertThrows(IllegalArgumentException.class,()->new SelectionReadService.PatchSendBinding("00000000-0000-0000-0000-000000000000","a".repeat(64),null,0,"c".repeat(64),"d".repeat(64),"e".repeat(64),"1".repeat(64),"f".repeat(64)));}
    @Test void monotonicClockWrapKeepsElapsedAgeCorrect(){long origin=Long.MAX_VALUE-10;var life=new SelectionCaptureLifetime<>(original,player,origin);assertFalse(life.expired(origin+20));assertTrue(life.expired(origin+SelectionCaptureLifetime.IDLE_NANOS));}
}
