package dev.voxelstudio.selection;

import com.google.gson.*;
import dev.voxelstudio.Asset;
import org.junit.jupiter.api.Test;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.concurrent.CancellationException;
import static org.junit.jupiter.api.Assertions.*;

final class WorldPatchPreviewTest {
    private static final String HASH="a".repeat(64),PATCH="b".repeat(64);
    private SelectionRegion r(int x,int y,int z,int xx,int yy,int zz){return new SelectionRegion(new SelectionRegion.Point(x,y,z),new SelectionRegion.Point(xx,yy,zz));}
    private WorldSelection selection(){var box=r(-20,-3,-4,4,4,4);return new WorldSelection(new WorldSelection.WorldIdentity("test","minecraft:overworld",-64,320),7,box,box,List.of());}
    private String sha(JsonElement e){try{return Asset.sha(Asset.canonical(e).getBytes(StandardCharsets.UTF_8));}catch(Exception error){throw new RuntimeException(error);}}
    private JsonObject fixture(){
        var v=new JsonObject();v.addProperty("format","WorldPatchPreview");v.addProperty("version",1);v.addProperty("policy","static-patch-preview-data-v1");v.addProperty("snapshotHash",HASH);v.addProperty("selectionHash",sha(selection().json()));v.addProperty("patchHash",PATCH);v.add("world",selection().world().json());v.addProperty("selectionRevision",7);v.addProperty("contextRevision",9);v.addProperty("coordinateSpace","original-world-absolute");
        for(var key:List.of("movable","canAuthorizePlacement","serverBaselineVerified","physicsVerified","worldRendered"))v.addProperty(key,false);
        v.add("bounds",r(-17,-1,-1,-14,1,1).json());v.add("palette",JsonParser.parseString("[\"minecraft:air\",\"minecraft:glass\",\"minecraft:stone\"]"));
        v.add("sections",JsonParser.parseString("[{\"x\":-2,\"y\":-1,\"z\":-1,\"rows\":[[4095,1,0,1]]},{\"x\":-1,\"y\":-1,\"z\":-1,\"rows\":[[4080,0,2,0]]},{\"x\":-1,\"y\":0,\"z\":0,\"rows\":[[1,2,1,2]]}]"));
        v.add("summary",JsonParser.parseString("{\"writes\":3,\"counts\":{\"added\":1,\"removed\":1,\"replaced\":1},\"omittedCells\":\"keep\",\"explicitKeeps\":0}"));return rehash(v);
    }
    private JsonObject rehash(JsonObject v){v.remove("previewHash");v.addProperty("previewHash",sha(v));return v;}
    private WorldPatchPreview.Binding binding(JsonObject v){return new WorldPatchPreview.Binding(selection(),9,HASH,sha(selection().json()),PATCH,v.get("previewHash").getAsString());}
    private byte[] bytes(JsonObject v){return v.toString().getBytes(StandardCharsets.UTF_8);}
    private WorldPatchPreview read(){var v=fixture();return WorldPatchPreview.parse(bytes(v),binding(v));}
    @Test void negativeSectionsKeepOriginalAbsoluteCoordinates(){var p=read();assertEquals(3,p.totalWrites());assertEquals(new SelectionRegion.Point(-17,-1,-1),p.sections().get(0).rows().get(0).position());assertNotNull(p.at(new SelectionRegion.Point(-16,-1,-1)));assertNotNull(p.at(new SelectionRegion.Point(-15,0,0)));assertEquals(1,p.counts().get(WorldPatchPreview.Difference.REMOVED));assertFalse(p.movable());assertFalse(p.canAuthorizePlacement());}
    @Test void removedAndReplacedStatesRemainAvailableInAllViews(){var p=read();var removed=p.sections().get(0).rows().get(0);var replaced=p.sections().get(2).rows().get(0);assertEquals("minecraft:glass",WorldPatchPreview.displayState(removed,WorldPatchPreview.Mode.CHANGES,true));assertNull(WorldPatchPreview.displayState(removed,WorldPatchPreview.Mode.AFTER,false));assertEquals("minecraft:stone",WorldPatchPreview.displayState(replaced,WorldPatchPreview.Mode.CHANGES,true));assertEquals("minecraft:glass",WorldPatchPreview.displayState(replaced,WorldPatchPreview.Mode.CHANGES,false));assertNull(WorldPatchPreview.displayState(replaced,WorldPatchPreview.Mode.BEFORE,false));}
    @Test void viewFiltersDoNotChangePatchScopeOrOmittedKeep(){var p=read();var f=new WorldPatchPreview.Filter(WorldPatchPreview.Mode.CHANGES,-1,0,Set.of(WorldPatchPreview.Difference.ADDED));assertEquals(1,p.visible(f).size());assertEquals(3,p.totalWrites());assertNull(p.at(new SelectionRegion.Point(-14,0,0)));assertEquals(0,p.visible(new WorldPatchPreview.Filter(WorldPatchPreview.Mode.AFTER,-64,320,Set.of())).size());}
    @Test void staleWorldSelectionContextAndIdentityFail(){var v=fixture();for(var key:List.of("snapshotHash","patchHash","previewHash","selectionHash")){var wrong=v.deepCopy();wrong.addProperty(key,"c".repeat(64));assertThrows(IllegalArgumentException.class,()->WorldPatchPreview.parse(bytes(wrong),binding(v)));}for(var key:List.of("selectionRevision","contextRevision")){var wrong=v.deepCopy();wrong.addProperty(key,10);rehash(wrong);assertThrows(IllegalArgumentException.class,()->WorldPatchPreview.parse(bytes(wrong),binding(wrong)));}var wrong=v.deepCopy();wrong.getAsJsonObject("world").addProperty("dimension","minecraft:the_nether");rehash(wrong);assertThrows(IllegalArgumentException.class,()->WorldPatchPreview.parse(bytes(wrong),binding(wrong)));}
    @Test void rehashedClassificationMismatchFails(){var v=fixture();v.getAsJsonArray("sections").get(0).getAsJsonObject().getAsJsonArray("rows").get(0).getAsJsonArray().set(3,new JsonPrimitive(0));rehash(v);assertThrows(IllegalArgumentException.class,()->WorldPatchPreview.parse(bytes(v),binding(v)));}
    @Test void transformedOrAuthorityBearingPayloadNeverBecomesAsset(){for(var key:List.of("movable","canAuthorizePlacement","serverBaselineVerified","physicsVerified","worldRendered")){var v=fixture();v.addProperty(key,true);rehash(v);assertThrows(IllegalArgumentException.class,()->WorldPatchPreview.parse(bytes(v),binding(v)));}for(var key:List.of("rotation","mirror","anchor","applyScope")){var v=fixture();v.addProperty(key,1);rehash(v);assertThrows(IllegalArgumentException.class,()->WorldPatchPreview.parse(bytes(v),binding(v)));}}
    @Test void unknownCoordinatesAndRowDuplicateRejectWithoutCropping(){var v=fixture();var s=v.getAsJsonArray("sections");s.add(s.get(0).deepCopy());rehash(v);assertThrows(IllegalArgumentException.class,()->WorldPatchPreview.parse(bytes(v),binding(v)));var wrong=fixture();wrong.getAsJsonObject("bounds").getAsJsonArray("max").set(0,new JsonPrimitive(5));rehash(wrong);assertThrows(IllegalArgumentException.class,()->WorldPatchPreview.parse(bytes(wrong),binding(wrong)));}
    @Test void malformedAndFractionalNumbersDoNotTruncate(){for(var key:List.of("version","selectionRevision","contextRevision")){var v=fixture();v.addProperty(key,1.5);rehash(v);assertThrows(IllegalArgumentException.class,()->WorldPatchPreview.parse(bytes(v),binding(v)));}var v=fixture();v.addProperty("movable","false");rehash(v);assertThrows(IllegalArgumentException.class,()->WorldPatchPreview.parse(bytes(v),binding(v)));}
    @Test void hashCheckDetectsUnchangedIdentityWithAlteredGeometry(){var v=fixture();var expected=binding(v);v.getAsJsonArray("sections").get(0).getAsJsonObject().addProperty("x",-3);assertThrows(IllegalArgumentException.class,()->WorldPatchPreview.parse(bytes(v),expected));}
    @Test void canonicalCountsPaletteAndBoundsAreRequired(){var v=fixture();v.getAsJsonObject("summary").getAsJsonObject("counts").addProperty("added",2);rehash(v);assertThrows(IllegalArgumentException.class,()->WorldPatchPreview.parse(bytes(v),binding(v)));var duplicate=fixture();duplicate.getAsJsonArray("palette").set(2,new JsonPrimitive("minecraft:glass"));rehash(duplicate);assertThrows(IllegalArgumentException.class,()->WorldPatchPreview.parse(bytes(duplicate),binding(duplicate)));var bounds=fixture();bounds.getAsJsonObject("bounds").getAsJsonArray("max").set(0,new JsonPrimitive(-13));rehash(bounds);assertThrows(IllegalArgumentException.class,()->WorldPatchPreview.parse(bytes(bounds),binding(bounds)));}
    @Test void protectedScopeRejectedEvenWithFreshCallerHash(){var v=fixture();var original=selection();var guarded=new WorldSelection(original.world(),7,original.context(),original.edit(),List.of(r(-17,-1,-1,-16,0,0)));v.addProperty("selectionHash",sha(guarded.json()));rehash(v);var binding=new WorldPatchPreview.Binding(guarded,9,HASH,sha(guarded.json()),PATCH,v.get("previewHash").getAsString());assertThrows(IllegalArgumentException.class,()->WorldPatchPreview.parse(bytes(v),binding));}
    @Test void cancellationReturnsNoPartialPreview(){var v=fixture();assertThrows(CancellationException.class,()->WorldPatchPreview.parse(bytes(v),binding(v),()->true));}
    @Test void immutableRowsPaletteCountsAndFilters(){var p=read();assertThrows(UnsupportedOperationException.class,()->p.sections().clear());assertThrows(UnsupportedOperationException.class,()->p.sections().get(0).rows().clear());assertThrows(UnsupportedOperationException.class,()->p.palette().clear());assertThrows(UnsupportedOperationException.class,()->p.counts().clear());var categories=EnumSet.allOf(WorldPatchPreview.Difference.class);var f=new WorldPatchPreview.Filter(WorldPatchPreview.Mode.CHANGES,-1,1,categories);categories.clear();assertEquals(3,f.categories().size());}
    @Test void emptyAndOutOfHeightFiltersRejected(){var p=read();assertThrows(IllegalArgumentException.class,()->new WorldPatchPreview.Filter(WorldPatchPreview.Mode.AFTER,0,0,Set.of()));assertThrows(IllegalArgumentException.class,()->p.checked(new WorldPatchPreview.Filter(WorldPatchPreview.Mode.AFTER,-65,320,Set.of())));}
    @Test void specialStateStringsRetainedWithoutRotationOrNormalization(){var v=fixture();var palette=v.getAsJsonArray("palette");palette.set(1,new JsonPrimitive("minecraft:oak_stairs[facing=east,half=bottom,shape=straight,waterlogged=false]"));palette.set(2,new JsonPrimitive("minecraft:stone"));rehash(v);var p=WorldPatchPreview.parse(bytes(v),binding(v));assertEquals(palette.get(1).getAsString(),p.sections().get(0).rows().get(0).before());}
    @Test void oversizedBytesRejectedBeforeJsonParse(){var v=fixture();assertThrows(IllegalArgumentException.class,()->WorldPatchPreview.parse(new byte[SelectionLimits.snapshotBytes()+1],binding(v)));}
}
