package dev.voxelstudio.selection;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import java.util.*;
import com.google.gson.*;

final class WorldSelectionTest {
    private WorldSelection.WorldIdentity world(){return new WorldSelection.WorldIdentity("world_test","minecraft:overworld",-64,320);}
    private SelectionRegion r(int x,int y,int z,int xx,int yy,int zz){return new SelectionRegion(new SelectionRegion.Point(x,y,z),new SelectionRegion.Point(xx,yy,zz));}
    private WorldSelection selection(){return new WorldSelection(world(),3,r(-17,-2,-1,17,2,17),r(-2,-1,-1,2,1,2),List.of(r(-1,-1,0,0,1,1)));}
    @Test void halfOpenBoundsAndNegativeChunksHaveExactCoverage(){var s=selection();assertEquals(12,s.chunks().size());assertEquals(-2,s.chunks().get(0).x());assertEquals(-1,s.chunks().get(0).z());assertEquals(s.context().cells(),s.chunks().stream().mapToLong(c->c.region().cells()).sum());assertFalse(s.edit().contains(new SelectionRegion.Point(2,0,1)));assertTrue(s.protectedAt(new SelectionRegion.Point(-1,0,0)));assertFalse(s.protectedAt(new SelectionRegion.Point(0,0,0)));}
    @Test void selectedCornersIncludeBothBlocksWithoutSilentCropping(){assertEquals(r(-2,-1,-3,3,5,1),SelectionRegion.corners(new SelectionRegion.Point(2,4,0),new SelectionRegion.Point(-2,-1,-3)));assertEquals(1,SelectionRegion.corners(new SelectionRegion.Point(0,0,0),new SelectionRegion.Point(0,0,0)).cells());}
    @Test void heightsVolumeNonNestedAndProtectionAreRejected(){assertThrows(IllegalArgumentException.class,()->new WorldSelection(world(),0,r(0,-65,0,4,0,4),r(0,-64,0,1,-63,1),List.of()));assertThrows(IllegalArgumentException.class,()->new WorldSelection(world(),0,r(0,0,0,256,128,256),r(0,0,0,1,1,1),List.of()));assertThrows(IllegalArgumentException.class,()->new WorldSelection(world(),0,r(0,0,0,128,65,128),r(0,0,0,128,65,128),List.of()));assertThrows(IllegalArgumentException.class,()->new WorldSelection(world(),0,r(0,0,0,4,4,4),r(-1,0,0,2,2,2),List.of()));assertThrows(IllegalArgumentException.class,()->new WorldSelection(world(),0,r(0,0,0,4,4,4),r(1,1,1,2,2,2),List.of(r(-1,0,0,1,1,1))));}
    @Test void invalidIdentitiesVectorsAndRevisionsDoNotBecomePermission(){assertThrows(IllegalArgumentException.class,()->new WorldSelection.WorldIdentity("D:/private/world","minecraft:overworld",-64,320));assertThrows(IllegalArgumentException.class,()->new WorldSelection.WorldIdentity("world","wrong",-64,320));assertThrows(IllegalArgumentException.class,()->new SelectionRegion.Point(Integer.MIN_VALUE,0,0));assertThrows(IllegalArgumentException.class,()->r(0,0,0,0,1,1));assertThrows(IllegalArgumentException.class,()->new WorldSelection(world(),-1,r(0,0,0,4,4,4),r(1,1,1,2,2,2),List.of()));assertThrows(IllegalArgumentException.class,()->new WorldSelection(world(),9007199254740992L,r(0,0,0,4,4,4),r(1,1,1,2,2,2),List.of()));}
    @Test void immutableProtectionAndJsonContainNoWorldPathOrNbt(){var p=new ArrayList<SelectionRegion>();p.add(r(-1,-1,0,0,1,1));var s=new WorldSelection(world(),0,selection().context(),selection().edit(),p);p.clear();assertEquals(1,s.protectedRegions().size());assertThrows(UnsupportedOperationException.class,()->s.protectedRegions().clear());var o=s.json();assertEquals(Set.of("format","version","world","revision","context","edit","protected"),o.keySet());assertEquals("WorldSelection",o.get("format").getAsString());assertFalse(o.toString().contains("nbt"));}
    @Test void facesAndMovesRejectInvalidBoxes(){var r=r(-2,-2,-2,2,2,2);assertEquals(-3,r.move(0,-1).min().x());assertEquals(3,r.face(1,true,3).max().y());assertThrows(IllegalArgumentException.class,()->r.face(0,true,-2));assertThrows(IllegalArgumentException.class,()->r.move(3,1));}
    @Test void randomizedChunkCoverageMatchesExactVolumes(){var random=new Random(621);for(int i=0;i<100;i++){int x=random.nextInt(100)-50,y=random.nextInt(20)-10,z=random.nextInt(100)-50;var r=r(x,y,z,x+random.nextInt(20)+1,y+random.nextInt(20)+1,z+random.nextInt(20)+1);var s=new WorldSelection(world(),0,r,r,List.of());assertEquals(r.cells(),s.chunks().stream().mapToLong(c->c.region().cells()).sum());}}
    @Test void bundledLimitsKeepExpectedProductSafetyBoundaries(){assertEquals(2097152,SelectionLimits.contextCells());assertEquals(1048576,SelectionLimits.editCells());assertEquals(384,SelectionLimits.axis(1));assertEquals(16777216,SelectionLimits.snapshotBytes());assertEquals(4096,SelectionLimits.paletteStates());assertEquals(128,SelectionLimits.assemblyParts());}
    @Test void uiMutationIsAtomicAndNeverMovesOtherScopes(){var d=new SelectionDraft(world());d.region(r(0,0,0,20,20,20));d.target(SelectionDraft.Target.EDIT,-1);d.region(r(5,5,5,10,10,10));var before=d.selection();d.target(SelectionDraft.Target.CONTEXT,-1);assertThrows(IllegalArgumentException.class,()->d.face(0,true,8));assertEquals(before,d.selection());d.move(0,1);assertEquals(before.edit(),d.edit());assertEquals(1,d.context().min().x());}
    @Test void incompletePointSelectionInvalidatesSnapshotAndWorldChangesClearIt(){var d=new SelectionDraft(world());d.region(r(0,0,0,20,20,20));d.target(SelectionDraft.Target.EDIT,-1);d.region(r(5,5,5,10,10,10));long rev=d.revision();d.first(new SelectionRegion.Point(6,6,6));assertTrue(d.revision()>rev);assertThrows(IllegalStateException.class,d::selection);d.second(new SelectionRegion.Point(8,8,8));assertEquals(27,d.selection().edit().cells());d.world(new WorldSelection.WorldIdentity("new","minecraft:the_nether",0,256));assertNull(d.context());assertThrows(IllegalStateException.class,d::selection);}
    @Test void protectionCreationResizeAndClearAreExplicit(){var d=new SelectionDraft(world());d.region(r(0,0,0,20,20,20));d.target(SelectionDraft.Target.EDIT,-1);d.region(r(5,5,5,10,10,10));d.target(SelectionDraft.Target.PROTECTED,-1);d.region(r(5,5,5,6,6,6));assertEquals(0,d.protectionIndex());assertTrue(d.selection().protectedAt(new SelectionRegion.Point(5,5,5)));d.face(0,true,7);assertEquals(2,d.protectedRegions().get(0).cells());d.clear();assertTrue(d.protectedRegions().isEmpty());d.target(SelectionDraft.Target.CONTEXT,-1);d.clear();assertNull(d.edit());}
}
