package dev.voxelstudio.client;

import com.google.gson.*;
import dev.voxelstudio.selection.*;
import net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents;
import net.fabricmc.loader.api.FabricLoader;
import net.minecraft.block.Blocks;
import net.minecraft.client.MinecraftClient;
import net.minecraft.client.gui.screen.*;
import net.minecraft.client.gui.widget.*;
import net.minecraft.registry.RegistryKeys;
import net.minecraft.resource.DataConfiguration;
import net.minecraft.util.WorldSavePath;
import net.minecraft.util.math.BlockPos;
import net.minecraft.world.*;
import net.minecraft.world.gen.*;
import net.minecraft.world.level.LevelInfo;
import java.nio.file.*;
import java.util.*;

/** A separate test-only controller. Uses the ACTUAL installed production
 * Bridge and model. Only a NEW creative fixture world, one independently
 * confirmed model SEND, one independently confirmed application and undo.
 * It never installs a mock candidate or assumes a fixed model write count. */
final class InstalledWorldPatchAcceptance {
    private final Path output,game;private final JsonObject auth;private final String worldName;private final boolean live;
    private int stage,ticks;private boolean pending,done;private final long started=System.nanoTime();
    private SelectionReadService.Capture capture;private JsonObject reference,status;
    private WorldPatchCandidateReceipt.AuditableDownload candidate;
    private WorldPatchPlacementService.Operation apply;private WorldPatchUndoService.Operation undo;
    private dev.voxelstudio.WorldChangeTracker.Watch watch;
    private long previewRevision;private BlockPos laterEdit;private final JsonObject report=new JsonObject();
    static void start(MinecraftClient c,Path root){try{var test=new InstalledWorldPatchAcceptance(root);ClientTickEvents.END_CLIENT_TICK.register(test::tick);c.setScreen(new TitleScreen());}catch(Throwable e){try{var f=new JsonObject();f.addProperty("result","failed");f.addProperty("error",e.toString());Files.writeString(root.resolve("patch-failure.json"),f.toString(),StandardOpenOption.CREATE_NEW);}catch(Exception ignored){}e.printStackTrace();c.scheduleStop();}}
    private InstalledWorldPatchAcceptance(Path root)throws Exception{
        output=root.toAbsolutePath().normalize().toRealPath();game=FabricLoader.getInstance().getGameDir().toRealPath();auth=read(output.resolve("patch-authorization.json"));
        if(FabricLoader.getInstance().isDevelopmentEnvironment()||!game.equals(output.resolve("game"))||!auth.get("newWorldOnly").getAsBoolean()||!auth.get("fixtureSetupAuthorized").getAsBoolean()||!auth.get("independentUiConfirmationsAuthorized").getAsBoolean()||auth.get("formalWorldAuthorized").getAsBoolean())throw new IllegalStateException("Invalid NEW-world fixture authorization");
        String mode=auth.get("mode").getAsString();if(!Set.of("before-send","live").contains(mode))throw new IllegalStateException("Unknown installed patch mode");live=mode.equals("live");
        if(auth.get("maximumCalls").getAsInt()!=(live?1:0)||!auth.get("agent").getAsString().equals("codex")||!auth.get("model").getAsString().equals("gpt-6.1-sol")||!auth.get("effort").getAsString().equals("max"))throw new IllegalStateException("Exact authorized model and one-call budget required");
        var selected=StudioScreen.contextRecipient();if(!selected.get("agent").equals(auth.get("agent"))||!selected.get("model").equals(auth.get("model"))||!selected.get("effort").equals(auth.get("effort")))throw new IllegalStateException("Normal UI recipient changed after installation phase");
        worldName=auth.get("worldName").getAsString();if(!worldName.matches("installed-patch-fixture-[a-f0-9]{32}")||Files.exists(game.resolve("saves").resolve(worldName)))throw new IllegalStateException("Existing worlds are forbidden");
        var installation=read(output.resolve("installation-phase.json"));if(!installation.get("result").getAsString().equals("passed")||!installation.get("defaultBuiltinBridge").getAsBoolean()||!installation.get("productionJarSha256").equals(auth.get("productionJarSha256")))throw new IllegalStateException("Exact installed phase required");
        report.addProperty("mode",mode);report.addProperty("worldName",worldName);report.addProperty("developmentEnvironment",false);report.addProperty("defaultBuiltinBridge",true);
    }
    private static SelectionRegion region(int x,int y,int z,int xx,int yy,int zz){return new SelectionRegion(new SelectionRegion.Point(x,y,z),new SelectionRegion.Point(xx,yy,zz));}
    private void tick(MinecraftClient c){if(done)return;try{
        if(++ticks%20==0){var progress=new JsonObject();progress.addProperty("stage",stage);progress.addProperty("pending",pending);progress.addProperty("seconds",(System.nanoTime()-started)/1e9);progress.addProperty("screen",c.currentScreen==null?"none":c.currentScreen.getClass().getSimpleName());if(status!=null)progress.addProperty("modelState",status.get("state").getAsString());if(apply!=null)progress.add("apply",new Gson().toJsonTree(apply.status()));if(undo!=null)progress.add("undo",new Gson().toJsonTree(undo.status()));Files.writeString(output.resolve("patch-progress.json"),progress.toString());}
        // No elapsed deadline on an actual model turn. Unknown results are
        // retained and NEVER resubmitted; launcher observation is not a retry.
        if(pending)return;c.options.pauseOnLostFocus=false;
        if(stage==0){if(!(c.currentScreen instanceof TitleScreen)||c.getOverlay()!=null||ticks<40)return;c.options.getViewDistance().setValue(4);c.getTutorialManager().setStep(net.minecraft.client.tutorial.TutorialStep.NONE);var rules=new GameRules();rules.get(GameRules.RANDOM_TICK_SPEED).set(0,null);rules.get(GameRules.DO_MOB_SPAWNING).set(false,null);rules.get(GameRules.DO_DAYLIGHT_CYCLE).set(false,null);var info=new LevelInfo(worldName,GameMode.CREATIVE,false,Difficulty.PEACEFUL,true,rules,DataConfiguration.SAFE_MODE);c.createIntegratedServerLoader().createAndStart(worldName,info,new GeneratorOptions(4477,false,false),r->r.get(RegistryKeys.WORLD_PRESET).getOrThrow(WorldPresets.FLAT).createDimensionsRegistryHolder());stage=1;ticks=0;return;}
        if(c.player==null||c.getServer()==null)return;
        if(!c.getServer().getSavePath(WorldSavePath.ROOT).toRealPath().equals(game.resolve("saves").resolve(worldName).toRealPath()))throw new IllegalStateException("Entered a non-authorized save");var tool=StudioClient.SELECTION;
        if(stage==1){if(ticks<160||!tool.ready())return;pending=true;var server=c.getServer();var user=c.player.getUuid();server.execute(()->{try{var world=server.getPlayerManager().getPlayer(user).getServerWorld();
            // Explicit pre-Capture fixture, NOT AI output. A facade in C at
            // W's north face, read-only road and a protected original plinth.
            for(int z=-12;z<-8;z++)for(int x=-12;x<12;x++)world.setBlockState(new BlockPos(x,-61,z),(z==-10?Blocks.YELLOW_CONCRETE:Blocks.GRAY_CONCRETE).getDefaultState(),2);
            for(int y=-60;y<-53;y++)for(int x=-10;x<10;x++){if(x>=-1&&x<=1&&y<-57)continue;world.setBlockState(new BlockPos(x,y,6),(y==-60||x%4==0?Blocks.QUARTZ_BLOCK:Blocks.LIGHT_BLUE_STAINED_GLASS).getDefaultState(),2);}
            for(int y=-61;y<-58;y++)for(int z=3;z<5;z++)for(int x=-8;x<-6;x++)world.setBlockState(new BlockPos(x,y,z),Blocks.STONE_BRICKS.getDefaultState(),2);
            c.execute(()->{pending=false;report.addProperty("preCaptureEnvironmentFixture",true);c.player.getAbilities().flying=true;c.player.sendAbilitiesUpdate();c.player.refreshPositionAndAngles(-14,-51,-14,-40,30);stage=2;});
        }catch(Throwable e){c.execute(()->fail(c,e));}});return;}
        if(stage==2){tool.cancel();tool.mutate(()->{tool.draft.target(SelectionDraft.Target.CONTEXT,-1);tool.draft.region(region(-12,-62,-12,12,-50,12));tool.draft.target(SelectionDraft.Target.EDIT,-1);tool.draft.region(region(-8,-61,-6,8,-53,6));tool.draft.target(SelectionDraft.Target.PROTECTED,-1);tool.draft.region(region(-8,-61,3,-6,-58,5));});tool.read();stage=3;return;}
        if(stage==3){if(tool.readStatus()==null||tool.readStatus().state()!=SelectionReadService.State.READY)return;pending=true;tool.checkedCapture().whenComplete((value,error)->c.execute(()->{pending=false;if(error!=null){fail(c,error);return;}try{capture=value;Files.writeString(output.resolve("original-capture.json"),capture.payload(),StandardOpenOption.CREATE_NEW);report.addProperty("originalCaptureId",capture.id());tool.saveContext();stage=4;}catch(Throwable e){fail(c,e);}}));return;}
        if(stage==4){if(tool.contextBusy())return;if(tool.savedContext()==null)throw new IllegalStateException("Original context save failed: "+tool.message);c.setScreen(new WorldPatchTaskScreen(new SelectionScreen(new StudioScreen())));var prompts=c.currentScreen.children().stream().filter(e->e instanceof EditBoxWidget).map(e->(EditBoxWidget)e).toList();if(prompts.size()!=1)throw new IllegalStateException("Normal patch prompt required");prompts.get(0).setText(auth.get("prompt").getAsString());press(c,"准备逐格披露");stage=5;return;}
        if(stage==5){if(!(c.currentScreen instanceof WorldPatchReviewScreen))return;shot(c,"exact-content-review.png");press(c,"确认内容");stage=6;return;}
        if(stage==6){if(!(c.currentScreen instanceof StudioInfoScreen)||!active(c,"独立审核一次发送"))return;press(c,"独立审核一次发送");stage=7;return;}
        if(stage==7){if(!(c.currentScreen instanceof WorldPatchSendScreen)||!active(c,"确认发送 1 次"))return;shot(c,"independent-send-confirmation.png");report.addProperty("exactContentReviewUi",true);report.addProperty("independentSendReady",true);
            if(!live){report.addProperty("result","passed");report.addProperty("modelCalls",0);report.addProperty("patchWrites",0);report.addProperty("realModelPlayerFlowVerified",false);saveAndStop(c,"patch-report.json");return;}
            press(c,"确认发送 1 次");report.addProperty("independentSendPressedOnce",true);stage=8;return;}
        if(stage==8){if(!(c.currentScreen instanceof WorldPatchResultScreen result))return;reference=result.referenceForAudit();status=result.statusForAudit();write("original-send-reference.json",reference);result.close();c.setScreen(null);report.addProperty("closedPanelDuringGeneration",true);stage=9;return;}
        if(stage==9){if(ticks%40!=0)return;pending=true;StudioClient.BRIDGE.readPatchJob(reference).thenCompose(value->{status=value;return tool.checkedCapture();}).whenComplete((original,error)->c.execute(()->{pending=false;if(error!=null){fail(c,error);return;}try{
            if(original!=capture)throw new IllegalStateException("Live original Capture was replaced");String state=status.get("state").getAsString();if(WorldPatchJobReceipt.polling(status))return;
            write("original-terminal-status.json",status);if(!state.equals("completed-checked"))throw new IllegalStateException("Original model result is "+state+"; retained, zero re-SEND");
            report.addProperty("sameOriginalCapture",true);c.setScreen(new WorldPatchResultScreen(new SelectionScreen(new StudioScreen()),reference,status));press(c,"加载原位差异投影");stage=10;
        }catch(Throwable e){fail(c,e);}}));return;}
        if(stage==10){if(!(c.currentScreen instanceof WorldPatchPreviewScreen))return;candidate=StudioClient.PATCH_PREVIEW.candidate();if(candidate==null||!candidate.reference().equals(WorldPatchJobReceipt.candidate(reference,status)))throw new IllegalStateException("Candidate is not the actual original model response");
            Files.write(output.resolve("original-proposal.json"),candidate.originalResponse(),StandardOpenOption.CREATE_NEW);report.addProperty("candidateHash",candidate.reference().candidateHash());report.addProperty("patchHash",candidate.preview().binding().patchHash());
            pending=true;var server=c.getServer();var user=c.player.getUuid();server.execute(()->{try{watch=dev.voxelstudio.WorldChangeTracker.watch(server.getPlayerManager().getPlayer(user).getServerWorld(),capture.selection().context());previewRevision=watch.revision();c.execute(()->{pending=false;c.setScreen(null);ticks=0;stage=11;});}catch(Throwable e){c.execute(()->fail(c,e));}});return;}
        if(stage==11){if(ticks<60)return;if(StudioClient.PATCH_PREVIEW.preview()==null||watch.revision()!=previewRevision)throw new IllegalStateException("Read-only preview changed world or was lost");shot(c,"model-difference-preview.png");report.addProperty("readOnlyDifferencePreview",true);c.setScreen(new WorldPatchPlacementScreen(new SelectionScreen(new StudioScreen()),candidate));press(c,"准备原规则");stage=12;return;}
        if(stage==12){if(!active(c,"确认理解"))return;if(watch.revision()!=previewRevision)throw new IllegalStateException("Preparation mutated world");shot(c,"independent-placement-confirmation.png");press(c,"确认理解");press(c,"最终确认");report.addProperty("independentPlacementPressedOnce",true);stage=13;return;}
        if(stage==13){pending=true;WorldPatchPlacementService.current(c.getServer(),c.player.getUuid()).whenComplete((value,error)->c.execute(()->{pending=false;if(error!=null){fail(c,error);return;}if(value==null)return;apply=value;c.currentScreen.close();c.setScreen(null);report.addProperty("closedPanelDuringApplication",true);stage=14;}));return;}
        if(stage==14){if(!apply.result().isDone())return;var result=apply.result().getNow(null);if(result.state()!=WorldPatchPlacementService.State.COMPLETED||result.confirmed()<=0||result.confirmed()!=result.total())throw new IllegalStateException("Actual model patch did not complete: "+result);report.add("apply",new Gson().toJsonTree(result));watch.close();watch=null;dump(c,"after-apply-world.json",()->{c.setScreen(new WorldPatchOperationScreen(new SelectionScreen(new StudioScreen())));stage=15;});return;}
        if(stage==15){if(!active(c,"准备保护式撤销"))return;pending=true;var server=c.getServer();var user=c.player.getUuid();server.execute(()->{try{var world=server.getPlayerManager().getPlayer(user).getServerWorld();outer:for(var section:candidate.preview().sections())for(var row:section.rows()){if(row.after().equals("minecraft:diamond_block"))continue;var point=row.position();laterEdit=new BlockPos(point.x(),point.y(),point.z());world.setBlockState(laterEdit,Blocks.DIAMOND_BLOCK.getDefaultState(),2);break outer;}if(laterEdit==null)throw new IllegalStateException("No model changed cell available");var changed=new JsonObject();var position=new JsonArray();position.add(laterEdit.getX());position.add(laterEdit.getY());position.add(laterEdit.getZ());changed.add("position",position);changed.addProperty("state","minecraft:diamond_block");write("later-player-edit.json",changed);c.execute(()->{pending=false;press(c,"准备保护式撤销");stage=16;});}catch(Throwable e){c.execute(()->fail(c,e));}});return;}
        if(stage==16){if(!(c.currentScreen instanceof WorldPatchUndoScreen))return;press(c,"只读核验原封闭事务");stage=17;return;}
        if(stage==17){if(!active(c,"理解：保留后改"))return;shot(c,"independent-undo-confirmation.png");press(c,"理解：保留后改");press(c,"最终确认");report.addProperty("independentUndoPressedOnce",true);stage=18;return;}
        if(stage==18){pending=true;WorldPatchUndoService.current(c.getServer(),c.player.getUuid()).whenComplete((value,error)->c.execute(()->{pending=false;if(error!=null){fail(c,error);return;}if(value==null)return;undo=value;c.currentScreen.close();c.setScreen(null);stage=19;}));return;}
        if(stage==19){if(!undo.result().isDone())return;var result=undo.result().getNow(null);if(result.status().state()!=WorldPatchUndoService.State.COMPLETED||result.status().evaluated()!=apply.status().confirmed()||result.status().preserved()<1)throw new IllegalStateException("Actual protection undo failed: "+result);report.add("undo",new Gson().toJsonTree(result));dump(c,"after-undo-world.json",()->{stage=20;ticks=0;});return;}
        if(stage==20){if(ticks<20)return;shot(c,"model-after-undo.png");report.addProperty("result","passed");report.addProperty("modelCalls",1);report.addProperty("newWorldOnly",true);report.addProperty("realModelPlayerFlowVerified",true);saveAndStop(c,"patch-report.json");}
    }catch(Throwable e){fail(c,e);}}
    private void dump(MinecraftClient c,String name,Runnable next){pending=true;var server=c.getServer();var user=c.player.getUuid();server.execute(()->{try{var world=server.getPlayerManager().getPlayer(user).getServerWorld();var region=capture.selection().context();var rows=new JsonArray();for(int y=region.min().y();y<region.max().y();y++)for(int z=region.min().z();z<region.max().z();z++)for(int x=region.min().x();x<region.max().x();x++){var point=new BlockPos(x,y,z);var fact=BlockStateFacts.read(world.getBlockState(point));var row=new JsonObject();var position=new JsonArray();position.add(x);position.add(y);position.add(z);row.add("position",position);row.addProperty("state",fact.state());row.addProperty("blockEntity",fact.blockEntity());rows.add(row);}Files.writeString(output.resolve(name),rows.toString(),StandardOpenOption.CREATE_NEW);if(laterEdit!=null&&!world.getBlockState(laterEdit).isOf(Blocks.DIAMOND_BLOCK))throw new IllegalStateException("Undo overwrote later player edit");c.execute(()->{pending=false;next.run();});}catch(Throwable e){c.execute(()->fail(c,e));}});}
    private void saveAndStop(MinecraftClient c,String name){pending=true;var server=c.getServer();server.execute(()->{try{if(!server.saveAll(false,true,true))throw new IllegalStateException("Normal save not acknowledged");c.execute(()->{try{report.addProperty("savedAcknowledged",true);report.addProperty("formalWorldOpened",false);report.addProperty("worldDurabilityVerified",false);write(name,report);done=true;c.scheduleStop();}catch(Throwable e){fail(c,e);}});}catch(Throwable e){c.execute(()->fail(c,e));}});}
    private void fail(MinecraftClient c,Throwable error){if(done)return;done=true;if(watch!=null)watch.close();try{var failure=new JsonObject();failure.addProperty("result","failed");failure.addProperty("stage",stage);failure.addProperty("error",error.toString());failure.addProperty("modelSendPressed",report.has("independentSendPressedOnce"));failure.addProperty("noAutomaticReplay",true);write("patch-failure.json",failure);}catch(Exception ignored){}error.printStackTrace();c.scheduleStop();}
    private void write(String name,JsonObject value)throws Exception{Files.writeString(output.resolve(name),new GsonBuilder().setPrettyPrinting().create().toJson(value),StandardOpenOption.CREATE_NEW);}
    private static JsonObject read(Path file)throws Exception{return JsonParser.parseString(Files.readString(file)).getAsJsonObject();}
    private void shot(MinecraftClient c,String name)throws Exception{try(var image=net.minecraft.client.util.ScreenshotRecorder.takeScreenshot(c.getFramebuffer())){image.writeTo(output.resolve(name));}}
    private static boolean active(MinecraftClient c,String prefix){return c.currentScreen!=null&&c.currentScreen.children().stream().anyMatch(e->e instanceof ClickableWidget w&&w.visible&&w.active&&w.getMessage().getString().startsWith(prefix));}
    private static void press(MinecraftClient c,String prefix){var screen=c.currentScreen;if(screen==null)throw new IllegalStateException("Missing production screen");var buttons=screen.children().stream().filter(e->e instanceof ClickableWidget w&&w.visible&&w.active&&w.getMessage().getString().startsWith(prefix)).map(e->(ClickableWidget)e).toList();if(buttons.size()!=1)throw new IllegalStateException("Missing/ambiguous visible production button: "+prefix);var b=buttons.get(0);double x=b.getX()+b.getWidth()/2.0,y=b.getY()+b.getHeight()/2.0;if(!screen.mouseClicked(x,y,0))throw new IllegalStateException("Production UI click unhandled");screen.mouseReleased(x,y,0);}
}
