package dev.voxelstudio.client;
import com.google.gson.*;import dev.voxelstudio.*;import net.minecraft.client.MinecraftClient;import net.minecraft.block.*;import net.minecraft.util.math.BlockPos;import net.minecraft.state.property.Properties;import java.nio.file.*;import java.util.*;import java.util.concurrent.*;

/** Only called from the existing exact-directory gated isolated world self-test. */
final class SpecialBlockWorldTest {
 static CompletableFuture<JsonObject> run(MinecraftClient c,BlockPos anchor)throws Exception{
  var result=new CompletableFuture<JsonObject>();var report=new JsonObject();Path dir=net.fabricmc.loader.api.FabricLoader.getInstance().getGameDir().resolve("../build/test-fixtures/special-block-world-fixture").normalize();var asset=new Asset("special-world-fixture",JsonParser.parseString(Files.readString(dir.resolve("manifest.json"))).getAsJsonObject(),Files.readAllBytes(dir.resolve("cells.bin")));
  var p=new Placement(asset,anchor,1,true,0,true);var server=c.getServer();var id=c.player.getUuid();var dimension=c.world.getRegistryKey().getValue();
  server.execute(()->{var world=server.getPlayerManager().getPlayer(id).getServerWorld();var before=new HashMap<BlockPos,BlockState>();for(int i=0;i<asset.volume();i++)before.put(p.world(i),world.getBlockState(p.world(i)));
   java.util.function.Consumer<Boolean> verify=cancelled->{for(int i=0;i<asset.volume();i++)if(SpecialBlocks.door(p.state(i))){var state=world.getBlockState(p.world(i));if(SpecialBlocks.door(state)&&!SpecialBlocks.matching(state,world.getBlockState(p.world(i).up(SpecialBlocks.offset(state)))))throw new IllegalStateException("Door split after placement/cancellation");}if(!cancelled)for(int i=0;i<asset.volume();i++)if(asset.cell(i)!=0&&!world.getBlockState(p.world(i)).equals(p.state(i)))throw new IllegalStateException("Special block state changed in world");};
   java.util.function.Supplier<CompletableFuture<PlacementService.Result>> undo=()->{var future=new CompletableFuture<PlacementService.Result>();PlacementService.undo(server,id,r->{if(r.finished())future.complete(r);});return future;};
   java.util.function.Function<Boolean,CompletableFuture<PlacementService.Result>> build=cancel->{var future=new CompletableFuture<PlacementService.Result>();PlacementService.check(server,id,dimension,p).whenComplete((check,error)->{if(error!=null){future.completeExceptionally(error);return;}PlacementService.startChecked(server,id,dimension,p,check.token(),true,r->{if(cancel&&r.message().equals("Building"))PlacementService.cancel(server);if(r.finished()){if(r.changed()==0)future.completeExceptionally(new IllegalStateException(r.message()));else future.complete(r);}});});return future;};
   Runnable restored=()->{for(var e:before.entrySet())if(!world.getBlockState(e.getKey()).equals(e.getValue()))throw new IllegalStateException("Special block undo failed to restore original world");};
   CompletableFuture<Void> supportCheck;
   try{var unsupported=withoutSupport(dir,1);var noSupport=new Placement(unsupported,anchor,1,true,0,true);report.addProperty("unsupportedDoorPreviewAccepted",true);supportCheck=PlacementService.check(server,id,dimension,noSupport).handle((check,error)->{if(error==null)throw new IllegalStateException("Unsupported door was allowed to build");restored.run();report.addProperty("unsupportedDoorBuildRejectedWithoutWrites",true);return null;});}catch(Exception e){result.completeExceptionally(e);return;}
   supportCheck.thenCompose(v->build.apply(false)).thenCompose(r->{verify.accept(false);report.addProperty("specialStatesPlacedExactly",true);
    try{var keep=new Placement(withoutSupport(dir,0),anchor,1,true,0,true);return PlacementService.check(server,id,dimension,keep).thenApply(check->{report.addProperty("doorKeepUsesActualWorldSupport",true);return r;});}catch(Exception e){return CompletableFuture.failedFuture(e);}
   }).thenCompose(r->undo.get()).thenCompose(r->{restored.run();report.addProperty("specialStatesUndoRestored",true);report.addProperty("invisibleLightUndoRestored",true);return build.apply(true);}).thenCompose(r->{verify.accept(true);if(!r.message().contains("Cancelled"))throw new IllegalStateException("Cancellation not exercised");report.addProperty("doorCancellationKeepsPairs",true);return undo.get();}).thenCompose(r->{restored.run();return build.apply(false);}).thenCompose(r->{verify.accept(false);int lower=asset.index(0,1,0);BlockPos pos=p.world(lower);var state=world.getBlockState(pos);((DoorBlock)state.getBlock()).setOpen(null,world,state,pos,true);if(!world.getBlockState(pos).get(Properties.OPEN)||!world.getBlockState(pos.up()).get(Properties.OPEN))throw new IllegalStateException("Placed door cannot open normally");report.addProperty("doorInteractsNormally",true);
    BlockPos light=p.world(asset.index(1,1,7));if(!world.getBlockState(light).isOf(Blocks.LIGHT))throw new IllegalStateException("Missing invisible light probe");world.setBlockState(light,world.getBlockState(light).with(Properties.LEVEL_15,14),Block.NOTIFY_LISTENERS|Block.FORCE_STATE|Block.SKIP_DROPS);
    return undo.get();}).thenAccept(r->{if(r.conflicts()<3)throw new IllegalStateException("Undo did not preserve modified door halves and light level");verify.accept(true);report.addProperty("doorUndoConflictPreservesPair",true);BlockPos light=p.world(asset.index(1,1,7));if(!world.getBlockState(light).isOf(Blocks.LIGHT)||world.getBlockState(light).get(Properties.LEVEL_15)!=14)throw new IllegalStateException("Undo overwrote later light-level edit");report.addProperty("invisibleLightLaterEditPreserved",true);
    // Explicit fixture cleanup of deliberate user-like door edits, not production undo behavior.
    for(var e:before.entrySet())if(!world.getBlockState(e.getKey()).equals(e.getValue()))world.setBlockState(e.getKey(),e.getValue(),Block.NOTIFY_LISTENERS|Block.FORCE_STATE|Block.SKIP_DROPS);restored.run();result.complete(report);
   }).exceptionally(e->{result.completeExceptionally(e);return null;});
  });return result;
 }
 private static Asset withoutSupport(Path dir,int value)throws Exception{
  var manifest=JsonParser.parseString(Files.readString(dir.resolve("manifest.json"))).getAsJsonObject();byte[] cells=Files.readAllBytes(dir.resolve("cells.bin"));cells[0]=(byte)value;cells[1]=0;manifest.addProperty("setCount",manifest.get("setCount").getAsInt()-1);if(value==1)manifest.addProperty("clearCount",manifest.get("clearCount").getAsInt()+1);manifest.addProperty("cellsHash",Asset.sha(cells));manifest.remove("assetHash");manifest.addProperty("assetHash",Asset.sha(Asset.canonical(manifest).getBytes(java.nio.charset.StandardCharsets.UTF_8)));return new Asset("support-review-fixture",manifest,cells);
 }
}
