package dev.voxelstudio.client;

import com.google.gson.*;import dev.voxelstudio.*;import net.fabricmc.loader.api.FabricLoader;import net.minecraft.client.MinecraftClient;import net.minecraft.client.gui.screen.TitleScreen;import net.minecraft.util.math.BlockPos;import java.nio.file.*;import java.util.*;

/** Explicit opt-in dev fixture: asset-only four-view captures; no world or agent requests. */
final class StudioAssetRenderSelfTest {
 private static String[] ASSETS={"terraced-courtyard-study","timber-teahouse-study","special-block-world-fixture","baseline-019","design-020","scene-courtyard","scene-teahouse","scene-commercial","scene-cbd-224"};
 private static int stage,index,ticks,floorIndex;private static int[] floors;private static Asset asset;private static ProjectionRenderer renderer;private static Path output,captureRoot;private static JsonObject current,authorization;private static IsolatedTestWindow testWindow;private static final JsonArray evidence=new JsonArray();
 private static void authorize(Path game)throws Exception{
  Path development=game.getParent().getParent();boolean fork=development.getFileName().toString().matches("p3-selection-development-[a-f0-9]{32}");
  if(!fork){if(!game.toString().replace('\\','/').endsWith("/voxel/mod/run")||System.getProperty("voxelstudio.assetTestRoot")!=null)throw new IllegalStateException("Unsafe asset fixture root");return;}
  if(captureRoot!=null)return;
  if(!game.toRealPath().equals(development.resolve("mod/run").toRealPath()))throw new IllegalStateException("Redirected asset fixture game");
  var copy=JsonParser.parseString(Files.readString(development.resolve("development-workspace.json"))).getAsJsonObject();
  if(!"source-only-selection-development-workspace".equals(copy.get("type").getAsString())||!"passed".equals(copy.get("result").getAsString())||!copy.get("developmentOnly").getAsBoolean()||!Path.of(copy.get("root").getAsString()).equals(development)||copy.get("worldsCopied").getAsBoolean()||copy.get("accountDataCopied").getAsBoolean())throw new IllegalStateException("Unverified source-fork fixture");
  captureRoot=Path.of(System.getProperty("voxelstudio.assetTestRoot")).toRealPath();
  if(!captureRoot.getParent().equals(development.resolve("build").toRealPath())||!captureRoot.getFileName().toString().matches("checkpoint-preview-[a-f0-9]{32}"))throw new IllegalStateException("Unsafe checkpoint capture root");
  authorization=JsonParser.parseString(Files.readString(captureRoot.resolve("authorization.json"))).getAsJsonObject();
  if(!authorization.get("assetOnly").getAsBoolean()||!authorization.get("visibleWindowAuthorized").getAsBoolean()||authorization.get("modelCallsAllowed").getAsInt()!=0||authorization.get("worldsCopied").getAsBoolean()||!authorization.get("fixture").getAsString().matches("[a-z0-9-]{1,64}")||!authorization.get("fixture").getAsString().equals(System.getProperty("voxelstudio.assetFixtures"))||!"visible".equals(System.getProperty("voxelstudio.testWindowHideMode")))throw new IllegalStateException("Checkpoint preview authorization changed");
  var identity=new JsonObject();identity.addProperty("pid",ProcessHandle.current().pid());identity.addProperty("startedAt",ProcessHandle.current().info().startInstant().orElseThrow().toEpochMilli());identity.addProperty("instanceId",authorization.get("instanceId").getAsString());Files.writeString(captureRoot.resolve("process.json"),identity.toString(),StandardOpenOption.CREATE_NEW);
 }
 private static void frames(boolean material,String label)throws Exception{
  var views=AssetReviewCapture.captureEvidence(asset,renderer,material);var frames=current.getAsJsonArray("frames");
  for(int i=0;i<views.size();i++){byte[] png=Base64.getDecoder().decode(views.get(i).getAsString());String name=ASSETS[index]+"-"+label+"-"+i+".png";Files.write(output.resolve(name),png);var frame=new JsonObject();frame.addProperty("file",name);frame.addProperty("sha256",Asset.sha(png));frame.addProperty("materials",material);frame.addProperty("minLayer",renderer.minLayer);frame.addProperty("cutLayer",renderer.cutLayer);frames.add(frame);}
 }
 static void tick(MinecraftClient c){
  if(!FabricLoader.getInstance().isDevelopmentEnvironment()||!Boolean.getBoolean("voxelstudio.assettest")||stage==99)return;
  try{
   Path game=FabricLoader.getInstance().getGameDir().toAbsolutePath().normalize();if(c.world!=null||c.getServer()!=null)throw new IllegalStateException("Asset fixture must never load worlds");authorize(game);
   if(c.currentScreen instanceof net.minecraft.client.gui.screen.AccessibilityOnboardingScreen){c.options.onboardAccessibility=false;c.options.write();c.setScreen(new TitleScreen());return;}
   if(testWindow==null)testWindow=new IsolatedTestWindow(System.getProperty("voxelstudio.testWindowHideMode","transition"));
   long handle=c.getWindow().getHandle();testWindow.maintain(()->org.lwjgl.glfw.GLFW.glfwGetWindowAttrib(handle,org.lwjgl.glfw.GLFW.GLFW_VISIBLE)==org.lwjgl.glfw.GLFW.GLFW_TRUE,()->org.lwjgl.glfw.GLFW.glfwHideWindow(handle));
   if(stage==0){if(!(c.currentScreen instanceof TitleScreen)||c.getOverlay()!=null||++ticks<40)return;String requested=System.getProperty("voxelstudio.assetFixtures");if(requested!=null){ASSETS=requested.split(",");if(ASSETS.length<1||ASSETS.length>20)throw new IllegalArgumentException("Fixture count");for(String name:ASSETS)if(!name.matches("[a-z0-9-]{1,64}"))throw new IllegalArgumentException("Unsafe fixture name");}output=captureRoot==null?game.resolve("design-qa/"+System.currentTimeMillis()):captureRoot.resolve("frames");Files.createDirectories(output);stage=1;}
   else if(stage==1){Path source=game.resolve("../build/test-fixtures/"+ASSETS[index]).normalize();if(!source.toRealPath().equals(source))throw new IllegalStateException("Redirected asset fixture");byte[] manifestBytes=Files.readAllBytes(source.resolve("manifest.json")),cells=Files.readAllBytes(source.resolve("cells.bin"));if(authorization!=null&&(!Asset.sha(manifestBytes).equals(authorization.get("manifestSha256").getAsString())||!Asset.sha(cells).equals(authorization.get("cellsSha256").getAsString())))throw new IllegalStateException("Checkpoint fixture provenance changed");asset=new Asset("asset-render-fixture",JsonParser.parseString(new String(manifestBytes,java.nio.charset.StandardCharsets.UTF_8)).getAsJsonObject(),cells);renderer=new ProjectionRenderer();renderer.rebuild(new Placement(asset,BlockPos.ORIGIN,0,false,0,true));stage=2;ticks=0;}
   else if(stage==2||stage==4||stage==5){if(renderer.building){if(++ticks>2400)throw new IllegalStateException("Mesh timeout");return;}if(renderer.error!=null)throw new IllegalStateException(renderer.error);
    if(stage==2){current=new JsonObject();current.addProperty("fixture",ASSETS[index]);current.addProperty("assetHash",asset.hash);current.addProperty("diagnosticOnly",asset.diagnosticOnly);current.addProperty("faces",renderer.faceCount);current.add("frames",new JsonArray());frames(true,"mc");frames(false,"neutral");renderer.cutLayer=Math.min(asset.height-1,asset.height>128?7:5);renderer.rebuild(new Placement(asset,BlockPos.ORIGIN,0,false,0,true));stage=4;ticks=0;}
    else if(stage==4&&(asset.height>128||System.getProperty("voxelstudio.assetFloors")!=null)){frames(true,"section");String requested=System.getProperty("voxelstudio.assetFloors");floors=AssetFloorBands.parse(requested,asset.height,middleDenseLayer(asset));floorIndex=0;current.addProperty("floorBandSelection",requested==null?"Densest layer near midpoint; inspection aid, not proof of a usable office floor":"Explicit slab Y coordinates; geometry evidence, not a circulation certificate");beginFloor();}
    else if(stage==5){frames(true,"floor-y"+floors[floorIndex]);if(++floorIndex<floors.length)beginFloor();else finishAsset();}
    else{frames(true,"section");finishAsset();}
   }else if(stage==3){var report=new JsonObject();report.addProperty("result","passed");report.addProperty("version",StudioRuntimeVersion.loaded());report.addProperty("testWindowHideMode",testWindow.mode());report.addProperty("testWindowHideRequests",testWindow.hideRequests());report.addProperty("isolatedVisibleTestWindow","visible".equals(testWindow.mode()));report.addProperty("noWorldLoaded",true);report.addProperty("noGenerationSubmitted",true);report.addProperty("assetOnly",true);report.add("assets",evidence);Files.writeString(output.resolve("report.json"),new GsonBuilder().setPrettyPrinting().create().toJson(report));System.out.println("VOXEL_ASSET_RENDER_TEST "+output+" passed");stage=99;c.scheduleStop();}
  }catch(Exception e){stage=99;if(renderer!=null)renderer.close();System.err.println("VOXEL_ASSET_RENDER_TEST FAILED "+e);if(output!=null)try{Files.writeString(output.resolve("failure.txt"),e.toString());}catch(Exception ignored){}c.scheduleStop();}
 }
 private static void beginFloor(){renderer.minLayer=floors[floorIndex];renderer.cutLayer=renderer.minLayer+3;renderer.rebuild(new Placement(asset,BlockPos.ORIGIN,0,false,0,true));stage=5;ticks=0;}
 private static void finishAsset(){evidence.add(current);renderer.close();renderer=null;stage=++index<ASSETS.length?1:3;}
 private static int middleDenseLayer(Asset a){int best=a.height/2,count=-1;for(int y=Math.max(0,a.height/2-4);y<Math.min(a.height-3,a.height/2+5);y++){int n=0;for(int z=0;z<a.length;z++)for(int x=0;x<a.width;x++)if(a.cell(a.index(x,y,z))>=2)n++;if(n>count||n==count&&Math.abs(y-a.height/2)<Math.abs(best-a.height/2)){count=n;best=y;}}return best;}
}
