package dev.voxelstudio.client;

import com.google.gson.*;
import dev.voxelstudio.selection.*;
import java.nio.charset.StandardCharsets;
import java.util.*;

/** Exact P4 disclosure verification on the bounded background context lane.
 * Rebuilds all disclosed W/face facts from the original capture. Integrity is
 * neither model truth nor current-world/write authority. P3 consent is unused. */
final class WorldPatchTaskReceipt {
    static final int MAX_BYTES=2*SelectionLimits.snapshotBytes()+262144+32768;
    static void keys(JsonObject o,String... fields){if(o==null||!o.keySet().equals(Set.of(fields)))throw new IllegalStateException("改造回执字段不一致");}
    static String text(JsonObject o,String k){var v=o.get(k);if(v==null||!v.isJsonPrimitive()||!v.getAsJsonPrimitive().isString())throw new IllegalStateException("改造字符串无效："+k);return v.getAsString();}
    static long number(JsonObject o,String k){var v=o.get(k);if(v==null||!v.isJsonPrimitive()||!v.getAsJsonPrimitive().isNumber())throw new IllegalStateException("改造整数无效："+k);try{long n=v.getAsBigDecimal().longValueExact();if(n<0||n>9007199254740991L)throw new IllegalStateException("改造整数越界");return n;}catch(ArithmeticException e){throw new IllegalStateException("改造整数不可截断",e);}}
    static boolean flag(JsonObject o,String k){var v=o.get(k);if(v==null||!v.isJsonPrimitive()||!v.getAsJsonPrimitive().isBoolean())throw new IllegalStateException("改造标记无效："+k);return v.getAsBoolean();}
    static void no(JsonObject o,String... fields){for(var k:fields)if(flag(o,k))throw new IllegalStateException("改造回执不能授权："+k);}
    static void same(JsonElement a,JsonElement b){if(a==null||!a.equals(b))throw new IllegalStateException("原改造身份或披露数据改变");}
    static void digest(JsonObject o,String key){if(!text(o,key).matches("[a-f0-9]{64}"))throw new IllegalStateException("改造 hash 无效");}
    static void hash(JsonObject o,String field){digest(o,field);var c=o.deepCopy();c.remove(field);if(!ContextReceipt.jsonHash(c).equals(text(o,field)))throw new IllegalStateException("改造内容 hash 不一致");}
    static JsonObject intent(String agent,String model,String effort,String prompt){var v=ContextTaskReceipt.intent(agent,model,effort,prompt);v.addProperty("format","WorldPatchDesignIntent");v.addProperty("purpose","world-patch-design");return v;}
    private static final class Protocol {
        static final JsonObject VALUE=load();
        static final Map<String,JsonObject> BASE=base();
        private static JsonObject load(){try(var in=WorldPatchTaskReceipt.class.getResourceAsStream("/voxelstudio/world-patch-design-review-protocol.json")){
            if(in==null)throw new IllegalStateException("缺少本地改造协议");var v=WorldPatchCandidateReceipt.strictJson(new String(in.readAllBytes(),StandardCharsets.UTF_8),()->false).getAsJsonObject();
            keys(v,"version","rules","protocolHash","targetCatalog","baselineCatalog");if(number(v,"version")!=1)throw new IllegalStateException("改造协议版本不支持");
            var content=new JsonObject();content.addProperty("version",1);content.add("rules",v.get("rules"));if(!ContextReceipt.jsonHash(content).equals(text(v,"protocolHash")))throw new IllegalStateException("本地改造规则 hash 不一致");return v;
        }catch(java.io.IOException e){throw new IllegalStateException("不能读取本地改造规则",e);}}
        private static Map<String,JsonObject> base(){var result=new HashMap<String,JsonObject>();for(var e:VALUE.getAsJsonArray("baselineCatalog")){var v=e.getAsJsonObject();result.put(text(v,"id"),v.getAsJsonObject("properties"));}return Map.copyOf(result);}
    }
    static String protocolHash(){return text(Protocol.VALUE,"protocolHash");}
    static JsonObject verify(SelectionReadService.Capture capture,JsonObject saved,JsonObject intent,JsonObject response){
        if(capture.canAuthorizePlacement())throw new IllegalStateException("不是只读快照");ContextReceipt.verify(capture,capture.payload().getBytes(StandardCharsets.UTF_8),saved);
        same(intent,intent(text(intent,"agent"),text(intent,"model"),text(intent,"effort"),text(intent,"prompt")));
        if(ContextReceipt.canonicalJson(response).getBytes(StandardCharsets.UTF_8).length>MAX_BYTES)throw new IllegalStateException("改造披露超额，不截断");
        keys(response,"format","version","purpose","contextId","payloadSha256","recordHash","recordExpiresAt","snapshotHash","selectionHash","summaryHash","identity","task","taskHash","sourceAuthority","summaryConsentTransferable","modelSent","sendingImplemented","serverBaselineVerified","canAuthorizePlacement","taskDisclosureHash");
        if(!text(response,"format").equals("SavedWorldPatchTaskDisclosure")||number(response,"version")!=1||!text(response,"purpose").equals("world-patch-design"))throw new IllegalStateException("不是独立改造披露");
        no(response,"summaryConsentTransferable","modelSent","sendingImplemented","serverBaselineVerified","canAuthorizePlacement");hash(response,"taskDisclosureHash");
        var record=saved.getAsJsonObject("record");for(var k:List.of("payloadSha256","recordHash","snapshotHash","selectionHash","summaryHash","identity","sourceAuthority"))same(response.get(k),record.get(k));
        same(response.get("recordExpiresAt"),record.get("expiresAt"));if(!text(response,"contextId").equals(capture.id()))throw new IllegalStateException("改造快照 ID 改变");
        var task=response.getAsJsonObject("task");keys(task,"format","version","request","requestHash","disclosure","modelSent","sendingImplemented","serverBaselineVerified","canAuthorizePlacement","taskHash");
        if(!text(task,"format").equals("WorldPatchDesignPreparedTask")||number(task,"version")!=1)throw new IllegalStateException("改造任务版本不支持");no(task,"modelSent","sendingImplemented","serverBaselineVerified","canAuthorizePlacement");hash(task,"taskHash");same(task.get("taskHash"),response.get("taskHash"));
        var request=task.getAsJsonObject("request");keys(request,"format","version","purpose","snapshotHash","selectionHash","designInputHash","protocolHash","world","selectionRevision","contextRevision","intent","promptSha256");
        if(!text(request,"format").equals("WorldPatchDesignTask")||number(request,"version")!=1||!text(request,"purpose").equals("world-patch-design")||!ContextReceipt.jsonHash(request).equals(text(task,"requestHash")))throw new IllegalStateException("精确改造任务改变");
        same(request.get("intent"),intent);same(request.get("world"),capture.selection().world().json());
        for(var k:List.of("snapshotHash","selectionHash"))same(request.get(k),record.get(k));
        if(number(request,"selectionRevision")!=capture.selection().revision()||number(request,"contextRevision")!=capture.contextRevision()||!text(request,"protocolHash").equals(protocolHash()))throw new IllegalStateException("改造来源版本或规则改变");
        var d=task.getAsJsonObject("disclosure");keys(d,"format","version","purpose","requestHash","recipient","maximumCalls","world","context","edit","protected","selectionRevision","contextRevision","designInputHash","protocolHash","transmittedData","excludedData","cells","modelPrompt","modelPromptUtf8Bytes","promptSha256","sourceAuthority","resultAuthority","summaryConsentTransferable","automaticRetry","modelSent","sendingImplemented","canAuthorizePlacement","disclosureHash");
        if(!text(d,"format").equals("WorldPatchDesignDisclosure")||number(d,"version")!=1||!text(d,"purpose").equals("world-patch-design")||number(d,"maximumCalls")!=1)throw new IllegalStateException("改造用途/预算改变");
        no(d,"summaryConsentTransferable","automaticRetry","modelSent","sendingImplemented","canAuthorizePlacement");hash(d,"disclosureHash");same(d.get("requestHash"),task.get("requestHash"));
        var recipient=new JsonObject();for(var k:List.of("agent","model","effort"))recipient.add(k,intent.get(k));same(d.get("recipient"),recipient);
        for(var k:List.of("world","selectionRevision","contextRevision","designInputHash","protocolHash","promptSha256"))same(d.get(k),request.get(k));
        var selection=capture.selection().json();for(var k:List.of("context","edit","protected"))same(d.get(k),selection.get(k));
        same(d.get("transmittedData"),JsonParser.parseString("[\"exact-user-task-and-rules\",\"absolute-context-edit-protection-coordinates\",\"opaque-world-id-dimension-and-revisions\",\"whole-W-exact-block-state-and-protection-facts\",\"six-already-captured-adjacent-face-slabs\",\"context-material-counts-coverage-and-height-LOD\",\"supported-target-state-catalog\"]"));
        same(d.get("excludedData"),JsonParser.parseString("[\"NBT\",\"container-items\",\"sign-book-text\",\"entities\",\"save-paths\",\"screenshots\",\"diagonal-neighbor-cells\"]"));
        if(!text(d,"sourceAuthority").equals("client-captured-block-facts-not-current-server-attestation")||!text(d,"resultAuthority").equals("untrusted-proposal-only-no-world-writes"))throw new IllegalStateException("改造披露不能变成当前服务器证明");
        String prompt=text(d,"modelPrompt"),prefix=text(Protocol.VALUE,"rules")+"\n\n";byte[] wire=prompt.getBytes(StandardCharsets.UTF_8);
        if(!prompt.startsWith(prefix)||wire.length!=number(d,"modelPromptUtf8Bytes")||!ContextReceipt.sha256(wire).equals(text(d,"promptSha256")))throw new IllegalStateException("模型实际输入/规则/字节改变");
        var data=WorldPatchCandidateReceipt.strictJson(prompt.substring(prefix.length()),()->Thread.currentThread().isInterrupted()).getAsJsonObject();keys(data,"userTask","input");same(data.get("userTask"),intent.get("prompt"));
        var input=data.getAsJsonObject("input");keys(input,"format","version","policy","snapshotHash","selectionHash","contextRevision","world","context","edit","protected","contextSummary","exactBaseline","targetCatalog","protocolHash","privacy","modelSent","canAuthorizePlacement","serverBaselineVerified","physicsVerified","designInputHash");
        if(!text(input,"format").equals("WorldPatchDesignInput")||number(input,"version")!=1||!text(input,"policy").equals("static-proposal-data-v1")||!text(input,"privacy").equals("context-summary-plus-exact-W-and-six-face-neighbors-block-facts-only"))throw new IllegalStateException("精确输入用途改变");
        no(input,"modelSent","canAuthorizePlacement","serverBaselineVerified","physicsVerified");hash(input,"designInputHash");
        for(var k:List.of("snapshotHash","selectionHash","world","contextRevision","designInputHash","protocolHash"))same(input.get(k),request.get(k));for(var k:List.of("context","edit","protected"))same(input.get(k),selection.get(k));
        same(input.get("contextSummary"),saved.get("summary"));same(input.get("targetCatalog"),Protocol.VALUE.get("targetCatalog"));
        var baseline=baseline(capture);same(input.get("exactBaseline"),baseline);var cells=new JsonObject();cells.addProperty("context",capture.selection().context().cells());cells.addProperty("edit",capture.selection().edit().cells());
        cells.add("exactKnown",baseline.get("knownCells"));cells.add("exactUnknown",baseline.get("unknownCells"));var faces=new JsonArray();for(var r:baseline.getAsJsonArray("regions")){var v=r.getAsJsonObject();if(text(v,"role").equals("read-only-neighbor")){var f=new JsonObject();for(var k:List.of("face","region","cells"))f.add(k,v.get(k));faces.add(f);}}
        cells.add("adjacentFaces",faces);cells.add("missingFaces",baseline.get("missingFaces"));same(d.get("cells"),cells);return response;
    }
    private static JsonObject region(int[] min,int[] max){var v=new JsonObject();v.add("min",point(min));v.add("max",point(max));return v;}
    private static JsonArray point(int[] p){var a=new JsonArray();for(int n:p)a.add(n);return a;}
    private static int[] point(JsonArray a){if(a.size()!=3)throw new IllegalStateException("坐标不是三轴");return new int[]{a.get(0).getAsInt(),a.get(1).getAsInt(),a.get(2).getAsInt()};}
    private record Chunk(JsonObject value,int[] min,int[] max,long[] ends){JsonObject at(int x,int y,int z){if(text(value,"coverage").equals("unknown"))return null;long offset=((long)y-min[1])*(max[0]-min[0])*(max[2]-min[2])+((long)z-min[2])*(max[0]-min[0])+x-min[0];int lo=0,hi=ends.length-1;while(lo<hi){int mid=(lo+hi)>>>1;if(ends[mid]>offset)hi=mid;else lo=mid+1;}return value.getAsJsonArray("palette").get(value.getAsJsonArray("runs").get(lo).getAsJsonArray().get(0).getAsInt()).getAsJsonObject();}}
    private static JsonObject baseline(SelectionReadService.Capture capture){
        var data=WorldPatchCandidateReceipt.strictJson(capture.payload(),()->Thread.currentThread().isInterrupted()).getAsJsonObject();var chunks=new HashMap<String,Chunk>();var c=capture.selection().context();
        for(var item:data.getAsJsonObject("capture").getAsJsonArray("chunks")){var v=item.getAsJsonObject();int x=v.get("x").getAsInt(),z=v.get("z").getAsInt();int[] min={Math.max(c.min().x(),x*16),c.min().y(),Math.max(c.min().z(),z*16)},max={Math.min(c.max().x(),x*16+16),c.max().y(),Math.min(c.max().z(),z*16+16)};var runs=v.getAsJsonArray("runs");long[] ends=new long[runs.size()];long sum=0;for(int i=0;i<ends.length;i++)ends[i]=sum+=runs.get(i).getAsJsonArray().get(1).getAsLong();chunks.put(x+","+z,new Chunk(v,min,max,ends));}
        var w=capture.selection().edit();int[] lo={w.min().x(),w.min().y(),w.min().z()},hi={w.max().x(),w.max().y(),w.max().z()};var regions=new JsonArray();var edit=new JsonObject();edit.addProperty("role","edit-baseline");edit.add("region",w.json());regions.add(edit);var missing=new JsonArray();
        for(int axis=0;axis<3;axis++)for(int side:new int[]{-1,1}){int edge=side==-1?lo[axis]-1:hi[axis];var face=new JsonObject();face.addProperty("axis",axis);face.addProperty("side",side);if(edge<c.min().axis(axis)||edge>=c.max().axis(axis)){missing.add(face);continue;}int[] min=lo.clone(),max=hi.clone();min[axis]=edge;max[axis]=edge+1;var r=new JsonObject();r.addProperty("role","read-only-neighbor");r.add("face",face);r.add("region",region(min,max));regions.add(r);}
        var palette=new JsonArray();var indexes=new HashMap<String,Integer>();long known=0,unknown=0,visited=0;
        for(var item:regions){var r=item.getAsJsonObject();int[] min=point(r.getAsJsonObject("region").getAsJsonArray("min")),max=point(r.getAsJsonObject("region").getAsJsonArray("max"));var runs=new JsonArray();int previous=-2;
            for(int y=min[1];y<max[1];y++)for(int z=min[2];z<max[2];z++)for(int x=min[0];x<max[0];x++){
                if((visited++&1023)==0&&Thread.currentThread().isInterrupted())throw new java.util.concurrent.CancellationException("改造核验已取消");var chunk=chunks.get(Math.floorDiv(x,16)+","+Math.floorDiv(z,16));if(chunk==null)throw new IllegalStateException("原快照缺少区块");var raw=chunk.at(x,y,z);int index=-1;
                if(raw==null)unknown++;else{known++;String state=canonicalState(text(raw,"state"));boolean entity=flag(raw,"blockEntity");String protection=protection(state,entity),restriction=restriction(state);var fact=new JsonObject();fact.addProperty("state",state);fact.addProperty("blockEntity",entity);fact.add("blockProtection",protection==null?JsonNull.INSTANCE:new JsonPrimitive(protection));fact.add("patchStateRestriction",restriction==null?JsonNull.INSTANCE:new JsonPrimitive(restriction));String key=ContextReceipt.canonicalJson(fact);Integer old=indexes.get(key);if(old==null){index=palette.size();palette.add(fact);indexes.put(key,index);}else index=old;}
                if(index==previous){var last=runs.get(runs.size()-1).getAsJsonArray();last.set(1,new JsonPrimitive(last.get(1).getAsLong()+1));}else{var run=new JsonArray();run.add(index);run.add(1);runs.add(run);previous=index;}
            }r.addProperty("cells",(long)(max[0]-min[0])*(max[1]-min[1])*(max[2]-min[2]));r.add("runs",runs);
        }
        var out=new JsonObject();out.addProperty("cellOrder","y-z-x");out.addProperty("unknownPaletteIndex",-1);out.add("palette",palette);out.add("regions",regions);out.add("missingFaces",missing);out.addProperty("knownCells",known);out.addProperty("unknownCells",unknown);return out;
    }
    private static String canonicalState(String raw){int at=raw.indexOf('[');if(at<0)return raw;String id=raw.substring(0,at);var p=new TreeMap<String,String>();for(var part:raw.substring(at+1,raw.length()-1).split(",")){var kv=part.split("=",-1);if(kv.length!=2||p.put(kv[0],kv[1])!=null)throw new IllegalStateException("原方块状态无效");}return id+"["+p.entrySet().stream().map(e->e.getKey()+"="+e.getValue()).collect(java.util.stream.Collectors.joining(","))+"]";}
    private static String unsafe(String state){if(!state.matches("minecraft:[a-z0-9_]+(?:\\[[a-z0-9_=,]+\\])?"))return "Invalid block state";int at=state.indexOf('[');String id=at<0?state:state.substring(0,at);var base=Protocol.BASE.get(id);var props=new TreeMap<String,String>();if(at>=0)for(var part:state.substring(at+1,state.length()-1).split(",")){var kv=part.split("=",-1);if(kv.length!=2||props.put(kv[0],kv[1])!=null)return "Invalid/duplicate block property";}if(base==null||base.size()!=props.size())return "Unsupported/unsafe block state: "+state;for(var e:props.entrySet())if(!base.has(e.getKey())||!base.getAsJsonArray(e.getKey()).contains(new JsonPrimitive(e.getValue())))return "Unsupported block property: "+e.getKey()+"="+e.getValue();return null;}
    private static String protection(String state,boolean entity){if(entity)return "block-entity";if(!state.startsWith("minecraft:"))return "unclassified-mod-block";if(state.matches("^minecraft:(?:water|lava)(?:\\[.*|$)")||state.matches(".*\\bwaterlogged=true\\b.*"))return "dynamic-state";if(state.matches("^minecraft:[a-z_]+_(?:door|bed)\\[.*"))return "coupled-block";if(Set.of("air","cave_air","void_air","dirt","coarse_dirt","rooted_dirt","bedrock","obsidian","crying_obsidian").contains(state.substring(10)))return null;return unsafe(state)==null?null:"unclassified-vanilla-state";}
    private static String restriction(String state){if(Set.of("minecraft:air","minecraft:cave_air","minecraft:void_air").contains(state))return null;String error=unsafe(state);if(error!=null)return error;String id=state.split("\\[",2)[0];if(id.endsWith("_door")||id.endsWith("_trapdoor")||id.endsWith("_leaves")||id.equals("minecraft:light"))return "Patch v1 needs a separate coupling/support policy for "+id;return null;}
    static JsonObject confirmation(JsonObject prepared){var v=new JsonObject();v.addProperty("format","SavedWorldPatchDesignConfirmation");v.addProperty("version",1);v.addProperty("purpose","world-patch-design");v.addProperty("confirmed",true);for(var k:List.of("taskDisclosureHash","taskHash"))v.add(k,prepared.get(k));var t=prepared.getAsJsonObject("task");v.add("requestHash",t.get("requestHash"));v.add("disclosureHash",t.getAsJsonObject("disclosure").get("disclosureHash"));v.add("promptSha256",t.getAsJsonObject("request").get("promptSha256"));return v;}
    static JsonObject verifyFrozen(JsonObject prepared,JsonObject confirmation,JsonObject receipt){
        same(confirmation,confirmation(prepared));keys(receipt,"format","version","capsuleId","manifestHash","contextId","frozenAt","recordExpiresAt","recordHash","payloadSha256","snapshotHash","selectionHash","summaryHash","taskDisclosureHash","taskHash","requestHash","disclosureHash","promptSha256","confirmationHash","reviewHash","recipient","maximumCalls","bytes","state","sourceAuthority","summaryConsentTransferable","modelSent","sendingImplemented","serverBaselineVerified","canAuthorizePlacement");
        if(!text(receipt,"format").equals("FrozenWorldPatchTaskReceipt")||number(receipt,"version")!=1||!text(receipt,"state").equals("frozen-not-sent")||number(receipt,"maximumCalls")!=1)throw new IllegalStateException("不是原冻结改造任务");
        no(receipt,"summaryConsentTransferable","modelSent","sendingImplemented","serverBaselineVerified","canAuthorizePlacement");for(var k:List.of("capsuleId","manifestHash","recordHash","payloadSha256","snapshotHash","selectionHash","summaryHash","taskDisclosureHash","taskHash","requestHash","disclosureHash","promptSha256","confirmationHash","reviewHash"))digest(receipt,k);
        for(var k:List.of("contextId","recordExpiresAt","recordHash","payloadSha256","snapshotHash","selectionHash","summaryHash","taskDisclosureHash","taskHash","sourceAuthority"))same(receipt.get(k),prepared.get(k));
        for(var k:List.of("requestHash","disclosureHash","promptSha256"))same(receipt.get(k),confirmation.get(k));var task=prepared.getAsJsonObject("task");same(receipt.get("recipient"),task.getAsJsonObject("disclosure").get("recipient"));
        if(number(receipt,"frozenAt")==0||number(receipt,"frozenAt")>=number(receipt,"recordExpiresAt")||number(receipt,"frozenAt")>System.currentTimeMillis()+10000||number(receipt,"bytes")==0||number(receipt,"bytes")>512L*1024*1024)throw new IllegalStateException("原冻结时间或体积无效");
        if(!text(receipt,"confirmationHash").equals(ContextReceipt.jsonHash(confirmation))||!text(receipt,"reviewHash").equals(ContextReceipt.jsonHash(review(prepared,confirmation))))throw new IllegalStateException("原独立确认或审核 hash 改变");
        var id=new JsonObject();id.addProperty("version",1);for(var k:List.of("contextId","recordHash","taskDisclosureHash","confirmationHash","reviewHash"))id.add(k,receipt.get(k));if(!ContextReceipt.jsonHash(id).equals(text(receipt,"capsuleId")))throw new IllegalStateException("原 capsule 身份不一致");return receipt;
    }
    private static JsonObject review(JsonObject p,JsonObject confirmation){
        var inner=new JsonObject();inner.addProperty("format","WorldPatchDesignReviewedTask");inner.addProperty("version",1);inner.addProperty("purpose","world-patch-design");for(var k:List.of("taskHash","requestHash","disclosureHash","promptSha256"))inner.add(k,confirmation.get(k));inner.add("recipient",p.getAsJsonObject("task").getAsJsonObject("disclosure").get("recipient"));inner.addProperty("maximumCalls",1);inner.addProperty("state","reviewed-not-sent");for(var k:List.of("sendingImplemented","modelSent","canAuthorizePlacement"))inner.addProperty(k,false);inner.addProperty("reviewHash",ContextReceipt.jsonHash(inner));
        var outer=new JsonObject();outer.addProperty("format","SavedWorldPatchDesignReview");outer.addProperty("version",1);outer.addProperty("purpose","world-patch-design");for(var k:List.of("contextId","payloadSha256","recordHash","recordExpiresAt","snapshotHash","selectionHash","summaryHash","identity","taskDisclosureHash","taskHash","sourceAuthority"))outer.add(k,p.get(k));outer.add("requestHash",confirmation.get("requestHash"));outer.add("taskReview",inner);outer.addProperty("state","reviewed-not-sent");for(var k:List.of("modelSent","sendingImplemented","summaryConsentTransferable","serverBaselineVerified","canAuthorizePlacement"))outer.addProperty(k,false);return outer;
    }
    static String details(JsonObject p){var t=p.getAsJsonObject("task");var d=t.getAsJsonObject("disclosure");var intent=t.getAsJsonObject("request").getAsJsonObject("intent");
        return "独立的原位选区改造任务 · 当前仅审核内容\n\n模型："+text(intent,"agent")+" · "+text(intent,"model")+" · "+text(intent,"effort")
            +"\n最多 1 次模型调用，不自动纠错或重发。此确认只冻结原内容；发送还须独立点击确认。结果是待核验提案，不直接修改世界。\n\n提示词原文：\n"+text(intent,"prompt")
            +"\n\n外层 C："+d.get("context")+"\n内层 W："+d.get("edit")+"\n保护区："+d.get("protected")+"\n逐格已知："+d.getAsJsonObject("cells").get("exactKnown")+"；未知："+d.getAsJsonObject("cells").get("exactUnknown")
            +"\n\n这次会发送整个 W 的逐格方块状态、类型保护事实和 C 内已捕获的六个邻接面，还包含范围坐标、世界 opaque 身份、版本、环境摘要和支持材质目录。这不同于 P3 的摘要分析，旧确认不可沿用。\n不发送 NBT、容器物品、告示牌/书籍文字、实体、存档路径、截图或对角邻格。\n\n规则原文：\n"+text(Protocol.VALUE,"rules")
            +"\n\n完整模型输入可单独分页查看，不在游戏线程展开所有格。\n输入 UTF-8 字节："+number(d,"modelPromptUtf8Bytes")+"\n输入 hash："+text(d,"promptSha256")+"\n任务 hash："+text(p,"taskDisclosureHash")
            +"\n\n未知/保护格保持不动；PATCH v1 不支持门、活板门、流体、重力、红石和危险邻接状态。新建建筑的特殊方块能力仍保留。预览固定在原世界位置，不可旋转搬走；建造需后续独立确认和当前服务器 BEFORE 核验。";
    }
    private WorldPatchTaskReceipt(){}
}
