package dev.voxelstudio.client;

import com.google.gson.*;
import dev.voxelstudio.selection.*;
import net.fabricmc.loader.api.FabricLoader;
import net.minecraft.client.MinecraftClient;
import net.minecraft.client.gui.screen.*;
import net.minecraft.client.gui.widget.ClickableWidget;
import net.minecraft.registry.RegistryKeys;
import net.minecraft.resource.DataConfiguration;
import net.minecraft.util.WorldSavePath;
import net.minecraft.util.math.BlockPos;
import net.minecraft.world.*;
import net.minecraft.world.gen.*;
import net.minecraft.world.level.LevelInfo;
import net.minecraft.block.Blocks;
import java.nio.file.*;
import java.util.*;

/** Visible opt-in UI/real-server transaction acceptance in one NEW isolated
 * world. Fixture proposals are explicitly NOT model outputs. Never active in
 * a release environment or able to open an existing/formal save. */
final class WorldPatchTransactionSelfTest {
    private static Path output;private static String worldName;private static int stage,ticks,caseIndex;private static boolean pending;private static long started;
    private static SelectionReadService.Capture capture;private static WorldPatchPlacementService.Operation apply;private static WorldPatchUndoService.Operation undo;
    private static long captureReadyAt;private static JsonObject originalSendReference,originalSendStatus;
    private static WorldPatchCandidateReceipt.AuditableDownload candidate;private static dev.voxelstudio.WorldChangeTracker.Watch observed;private static long preparationRevision;
    private static final JsonObject report=new JsonObject();private static final JsonArray cases=new JsonArray();
    static boolean enabled(){return FabricLoader.getInstance().isDevelopmentEnvironment()&&System.getProperty("voxelstudio.patchTransactionTestRoot")!=null;}
    static boolean delayedSendEnabled(){return enabled()&&Boolean.getBoolean("voxelstudio.patchDelayedSend");}
    private static Path root()throws Exception{
        Path game=FabricLoader.getInstance().getGameDir().toRealPath(),development=game.getParent().getParent(),base=development.resolve("build").toRealPath();
        if(!development.getFileName().toString().matches("p3-selection-development-[a-f0-9]{32}")||!game.equals(development.resolve("mod/run").toRealPath()))throw new IllegalStateException("Not an independent development game");
        var copy=read(development.resolve("development-workspace.json"));if(!copy.get("developmentOnly").getAsBoolean()||!copy.get("result").getAsString().equals("passed"))throw new IllegalStateException("Missing source-copy receipt");
        Path result=Path.of(System.getProperty("voxelstudio.patchTransactionTestRoot")).toRealPath();if(!result.getParent().equals(base)||!result.getFileName().toString().matches("patch-transaction-game-[a-f0-9]{32}"))throw new IllegalStateException("Unsafe test output");
        var auth=read(result.resolve("authorization.json"));if(!auth.get("newWorldOnly").getAsBoolean()||!auth.get("visibleWindowAuthorized").getAsBoolean()||auth.get("modelCalls").getAsInt()!=0||!auth.get("explicitUiFixtureWrites").getAsBoolean()||auth.get("delayedSendFixture").getAsBoolean()!=delayedSendEnabled())throw new IllegalStateException("Invalid bounded fixture authorization");
        worldName=auth.get("worldName").getAsString();if(!worldName.matches("patch-transaction-fixture-[a-f0-9]{32}"))throw new IllegalStateException("Unsafe test world");return result;
    }
    static BridgeClient bridge()throws Exception{var r=root();var marker=read(r.resolve("offline-context-provider.json"));var connection=read(r.resolve("data/connection.json"));if(!marker.get("allProvidersReplaced").getAsBoolean()||marker.get("modelCallsAllowed").getAsInt()!=0||marker.get("pid").getAsLong()!=connection.get("pid").getAsLong())throw new IllegalStateException("Offline Bridge not bound");return new BridgeClient(r);}
    private static JsonObject read(Path file)throws Exception{return JsonParser.parseString(Files.readString(file)).getAsJsonObject();}
    private static SelectionRegion region(int x,int y,int z,int xx,int yy,int zz){return new SelectionRegion(new SelectionRegion.Point(x,y,z),new SelectionRegion.Point(xx,yy,zz));}
    static void tick(MinecraftClient c){if(!enabled()||stage==99)return;try{
        if(output==null){output=root();started=System.nanoTime();var p=new JsonObject();p.addProperty("pid",ProcessHandle.current().pid());p.addProperty("startedAt",ProcessHandle.current().info().startInstant().orElseThrow().toEpochMilli());Files.writeString(output.resolve("process.json"),p.toString(),StandardOpenOption.CREATE_NEW);}
        if(++ticks%20==0){var p=new JsonObject();p.addProperty("stage",stage);p.addProperty("case",caseIndex);p.addProperty("pending",pending);p.addProperty("seconds",(System.nanoTime()-started)/1e9);p.addProperty("screen",c.currentScreen==null?"none":c.currentScreen.getClass().getSimpleName());if(apply!=null)p.add("apply",new Gson().toJsonTree(apply.status()));if(undo!=null)p.add("undo",new Gson().toJsonTree(undo.status()));Files.writeString(output.resolve("progress.json"),p.toString());}
        if(System.nanoTime()-started>540_000_000_000L)throw new IllegalStateException("Transaction fixture exceeded nine minutes; preserve evidence, no replay");if(pending)return;
        c.options.pauseOnLostFocus=false;if(org.lwjgl.glfw.GLFW.glfwGetWindowAttrib(c.getWindow().getHandle(),org.lwjgl.glfw.GLFW.GLFW_VISIBLE)!=org.lwjgl.glfw.GLFW.GLFW_TRUE)throw new IllegalStateException("Test requires authorized visible window");
        if(stage==0){if(c.currentScreen instanceof net.minecraft.client.gui.screen.AccessibilityOnboardingScreen){c.options.onboardAccessibility=false;c.options.write();c.setScreen(new TitleScreen());return;}if(!(c.currentScreen instanceof TitleScreen)||c.getOverlay()!=null||ticks<40)return;Path target=FabricLoader.getInstance().getGameDir().resolve("saves").resolve(worldName);if(Files.exists(target))throw new IllegalStateException("Refusing existing world");c.options.getViewDistance().setValue(4);c.getTutorialManager().setStep(net.minecraft.client.tutorial.TutorialStep.NONE);var rules=new GameRules();rules.get(GameRules.RANDOM_TICK_SPEED).set(0,null);rules.get(GameRules.DO_MOB_SPAWNING).set(false,null);rules.get(GameRules.DO_DAYLIGHT_CYCLE).set(false,null);var info=new LevelInfo(worldName,GameMode.CREATIVE,false,Difficulty.PEACEFUL,true,rules,DataConfiguration.SAFE_MODE);c.createIntegratedServerLoader().createAndStart(worldName,info,new GeneratorOptions(4477,false,false),registries->registries.get(RegistryKeys.WORLD_PRESET).getOrThrow(WorldPresets.FLAT).createDimensionsRegistryHolder());stage=1;ticks=0;return;}
        if(c.player==null||c.getServer()==null)return;Path actual=c.getServer().getSavePath(WorldSavePath.ROOT).toRealPath(),allowed=FabricLoader.getInstance().getGameDir().resolve("saves").resolve(worldName).toRealPath();if(!actual.equals(allowed))throw new IllegalStateException("Entered a non-fixture save");var tool=StudioClient.SELECTION;
        if(stage==1){if(ticks<160||!tool.ready())return;if(Boolean.getBoolean("voxelstudio.iristest")){var api=Class.forName("net.irisshaders.iris.api.v0.IrisApi");if(!(boolean)api.getMethod("isShaderPackInUse").invoke(api.getMethod("getInstance").invoke(null)))throw new IllegalStateException("Iris shader not active");}report.addProperty("irisShaderPackActive",Boolean.getBoolean("voxelstudio.iristest"));c.player.getAbilities().flying=true;c.player.sendAbilitiesUpdate();c.player.refreshPositionAndAngles(-20,-38,-24,-35,25);stage=2;}
        if(stage==2){apply=null;undo=null;candidate=null;tool.cancel();tool.mutate(()->{tool.draft.target(SelectionDraft.Target.EDIT,-1);tool.draft.clear();tool.draft.target(SelectionDraft.Target.CONTEXT,-1);tool.draft.region(region(-14,-60,-14,14,-40,14));tool.draft.target(SelectionDraft.Target.EDIT,-1);tool.draft.region(region(-12,-58,-12,12,-42,12));});tool.read();stage=3;return;}
        if(stage==3){if(tool.readStatus()==null||tool.readStatus().state()!=SelectionReadService.State.READY)return;pending=true;tool.checkedCapture().whenComplete((value,error)->c.execute(()->{pending=false;if(error!=null){fail(c,error);return;}try{capture=value;captureReadyAt=System.nanoTime();Files.writeString(output.resolve("case-"+caseIndex+"-capture.json"),capture.payload(),StandardOpenOption.CREATE_NEW);tool.saveContext();stage=4;}catch(Exception e){fail(c,e);}}));return;}
        if(stage==4){if(tool.contextBusy())return;if(tool.savedContext()==null)throw new IllegalStateException("Context save failed: "+tool.message);Path file=output.resolve("case-"+caseIndex+"-fixture.json");if(!Files.exists(file))return;
            if(caseIndex==0&&delayedSendEnabled()){StudioScreen.prepareOfflinePatchTransaction();c.setScreen(new WorldPatchTaskScreen(new SelectionScreen(new TitleScreen())));stage=40;return;}
            var f=read(file);var preview=f.getAsJsonObject("preview");var saved=tool.savedContext().getAsJsonObject("record");if(!saved.get("snapshotHash").equals(preview.get("snapshotHash")))throw new IllegalStateException("Fixture not original captured data");var binding=new WorldPatchPreview.Binding(capture.selection(),capture.contextRevision(),saved.get("snapshotHash").getAsString(),saved.get("selectionHash").getAsString(),preview.get("patchHash").getAsString(),preview.get("previewHash").getAsString());var pin=f.getAsJsonObject("reference");var reference=new WorldPatchCandidateReceipt.Reference(pin.get("capsuleId").getAsString(),pin.get("manifestHash").getAsString(),pin.get("submissionHash").getAsString(),pin.get("runtimeHash").getAsString(),pin.get("responseHash").getAsString(),pin.get("candidateHash").getAsString(),binding);candidate=WorldPatchCandidateReceipt.parseCandidate(f.get("download").toString().getBytes(java.nio.charset.StandardCharsets.UTF_8),reference,()->false);StudioClient.PATCH_PREVIEW.showAuditableReadOnly(candidate);openPlacement(c);return;}
        if(stage==40){press(c,"准备逐格披露");stage=41;return;}
        if(stage==41){if(!(c.currentScreen instanceof WorldPatchReviewScreen))return;press(c,"确认内容");stage=42;return;}
        if(stage==42){if(!(c.currentScreen instanceof StudioInfoScreen)||!active(c,"独立审核一次发送"))return;press(c,"独立审核一次发送");stage=43;return;}
        if(stage==43){if(!(c.currentScreen instanceof WorldPatchSendScreen)||!active(c,"确认发送 1 次"))return;press(c,"确认发送 1 次");report.addProperty("explicitDelayedSendUi",true);stage=44;return;}
        if(stage==44){if(!(c.currentScreen instanceof WorldPatchResultScreen result))return;originalSendReference=result.referenceForAudit();originalSendStatus=result.statusForAudit();Files.writeString(output.resolve("case-0-original-send-reference.json"),originalSendReference.toString(),StandardOpenOption.CREATE_NEW);result.close();c.setScreen(null);report.addProperty("closedSendProgressCaptureRetained",true);stage=45;ticks=0;return;}
        if(stage==45){if(tool.readStatus()==null||tool.readStatus().state()!=SelectionReadService.State.READY)throw new IllegalStateException("Long original SEND lost its Capture: "+tool.statusText());if(ticks%40!=0)return;pending=true;
            StudioClient.BRIDGE.readPatchJob(originalSendReference).thenCompose(status->{originalSendStatus=status;return tool.checkedCapture();}).whenComplete((original,error)->c.execute(()->{pending=false;if(error!=null){fail(c,error);return;}try{if(original!=capture)throw new IllegalStateException("Original Capture replaced during long SEND");if(!WorldPatchTaskReceipt.text(originalSendStatus,"state").equals("completed-checked"))return;double age=(System.nanoTime()-captureReadyAt)/1e9;if(age<=300)throw new IllegalStateException("Long SEND fixture did not cross five real minutes");report.addProperty("sameCaptureAfterFiveMinutes",true);report.addProperty("delayedCaptureAgeSeconds",age);c.setScreen(new WorldPatchResultScreen(new SelectionScreen(new TitleScreen()),originalSendReference,originalSendStatus));press(c,"加载原位差异投影");stage=46;}catch(Exception e){fail(c,e);}}));return;}
        if(stage==46){if(!(c.currentScreen instanceof WorldPatchPreviewScreen))return;candidate=StudioClient.PATCH_PREVIEW.candidate();if(candidate==null||!candidate.reference().equals(WorldPatchJobReceipt.candidate(originalSendReference,originalSendStatus)))throw new IllegalStateException("Loaded candidate was not original SEND response");report.addProperty("productionCandidateFromMockSend",true);openPlacement(c);return;}
        if(stage==5){press(c,"准备原规则");if(active(c,"最终确认"))throw new IllegalStateException("Apply enabled before preparation and acknowledgement");stage=6;ticks=0;return;}
        if(stage==6){if(!active(c,"确认理解"))return;if(observed.revision()!=preparationRevision)throw new IllegalStateException("Preparation mutated world");screenshot(c,"case-"+caseIndex+"-final-confirmation.png");if(caseIndex==0&&!report.has("closingPreparationWritesNothing")){((WorldPatchPlacementScreen)c.currentScreen).close();if(observed.revision()!=preparationRevision)throw new IllegalStateException("Closing preparation wrote world");report.addProperty("closingPreparationWritesNothing",true);stage=7;ticks=0;return;}press(c,"确认理解");if(!active(c,"最终确认"))throw new IllegalStateException("Final acknowledgement not bound");press(c,"最终确认");if(active(c,"最终确认"))throw new IllegalStateException("Apply click was not one-use");report.addProperty("duplicateUiApplySuppressed",true);stage=8;return;}
        if(stage==7){if(ticks<20)return;c.setScreen(new WorldPatchPlacementScreen(new SelectionScreen(new TitleScreen()),candidate));stage=5;return;}
        if(stage==8){pending=true;WorldPatchPlacementService.current(c.getServer(),c.player.getUuid()).whenComplete((value,error)->c.execute(()->{pending=false;if(error!=null){fail(c,error);return;}if(value==null)return;apply=value;((WorldPatchPlacementScreen)c.currentScreen).close();c.setScreen(null);report.addProperty("closedProgressDoesNotCancelApply",true);stage=9;}));return;}
        if(stage==9){var status=apply.status();if(caseIndex==1&&status.confirmed()>0&&status.confirmed()<status.total()&&!report.has("inFlightConflictInjected")){pending=true;var server=c.getServer();var user=c.player.getUuid();server.execute(()->{try{var world=server.getPlayerManager().getPlayer(user).getServerWorld();if(!world.setBlockState(new BlockPos(13,-45,13),Blocks.DIAMOND_BLOCK.getDefaultState(),2))throw new IllegalStateException("Conflict fixture did not change environment");c.execute(()->{pending=false;report.addProperty("inFlightConflictInjected",true);});}catch(Exception e){c.execute(()->fail(c,e));}});return;}if(caseIndex==2&&status.confirmed()>0&&status.confirmed()<status.total()&&!report.has("explicitCancelDispatched")){c.setScreen(new WorldPatchOperationScreen(new SelectionScreen(new TitleScreen())));stage=90;return;}if(!apply.result().isDone())return;var result=apply.result().getNow(null);var expected=caseIndex==0?WorldPatchPlacementService.State.COMPLETED:caseIndex==1?WorldPatchPlacementService.State.CONFLICT:WorldPatchPlacementService.State.CANCELLED;if(result.state()!=expected||result.confirmed()<1||caseIndex==0&&result.confirmed()!=1000||caseIndex!=0&&result.confirmed()>=1000)throw new IllegalStateException("Unexpected native apply outcome: "+result);Files.writeString(output.resolve("case-"+caseIndex+"-apply.json"),new Gson().toJson(result),StandardOpenOption.CREATE_NEW);if(StudioClient.PATCH_PREVIEW.preview()!=null)throw new IllegalStateException("Handoff retained stale preview");observed.close();observed=null;c.setScreen(new WorldPatchOperationScreen(new SelectionScreen(new TitleScreen())));stage=10;return;}
        if(stage==90){if(!active(c,"显式取消当前事务"))return;press(c,"显式取消当前事务");report.addProperty("explicitCancelDispatched",true);c.currentScreen.close();c.setScreen(null);stage=9;return;}
        if(stage==10){if(!active(c,"准备保护式撤销"))return;screenshot(c,"case-"+caseIndex+"-apply-progress.png");if(caseIndex==0){pending=true;var server=c.getServer();var user=c.player.getUuid();server.execute(()->{try{var world=server.getPlayerManager().getPlayer(user).getServerWorld();world.setBlockState(new BlockPos(-12,-58,-12),Blocks.DIAMOND_BLOCK.getDefaultState(),2);world.setBlockState(new BlockPos(-9,-58,-12),Blocks.GOLD_BLOCK.getDefaultState(),2);c.execute(()->{pending=false;press(c,"准备保护式撤销");stage=11;});}catch(Exception e){c.execute(()->fail(c,e));}});return;}press(c,"准备保护式撤销");stage=11;return;}
        if(stage==11){press(c,"只读核验原封闭事务");if(active(c,"最终确认"))throw new IllegalStateException("Undo enabled without its independent acknowledgement");stage=12;return;}
        if(stage==12){if(!active(c,"理解：保留后改"))return;screenshot(c,"case-"+caseIndex+"-undo-confirmation.png");press(c,"理解：保留后改");press(c,"最终确认");if(active(c,"最终确认"))throw new IllegalStateException("Undo click remained active");stage=13;return;}
        if(stage==13){pending=true;WorldPatchUndoService.current(c.getServer(),c.player.getUuid()).whenComplete((value,error)->c.execute(()->{pending=false;if(error!=null){fail(c,error);return;}if(value==null)return;undo=value;((WorldPatchUndoScreen)c.currentScreen).close();c.setScreen(null);report.addProperty("closedProgressDoesNotCancelUndo",true);stage=14;}));return;}
        if(stage==14){if(!undo.result().isDone())return;var result=undo.result().getNow(null);var u=result.status();if(u.state()!=WorldPatchUndoService.State.COMPLETED||u.evaluated()!=apply.status().confirmed()||u.restored()+u.preserved()!=u.total()||caseIndex==0&&(u.preserved()<2||u.restored()<1)||caseIndex!=0&&u.preserved()!=0)throw new IllegalStateException("Unexpected native protection undo: "+result);Files.writeString(output.resolve("case-"+caseIndex+"-undo.json"),new Gson().toJson(result),StandardOpenOption.CREATE_NEW);pending=true;var server=c.getServer();var user=c.player.getUuid();server.execute(()->{try{var world=server.getPlayerManager().getPlayer(user).getServerWorld();var finalStates=new JsonArray();for(var section:candidate.preview().sections())for(var row:section.rows()){var p=row.position();var state=BlockStateFacts.read(world.getBlockState(new BlockPos(p.x(),p.y(),p.z())));var actualRow=new JsonObject();actualRow.add("position",p.json());actualRow.addProperty("state",state.state());actualRow.addProperty("blockEntity",state.blockEntity());finalStates.add(actualRow);}if(caseIndex==0&&(!world.getBlockState(new BlockPos(-12,-58,-12)).isOf(Blocks.DIAMOND_BLOCK)||!world.getBlockState(new BlockPos(-9,-58,-12)).isOf(Blocks.GOLD_BLOCK)))throw new IllegalStateException("Undo overwrote later target/neighbour edit");Files.writeString(output.resolve("case-"+caseIndex+"-final-states.json"),finalStates.toString(),StandardOpenOption.CREATE_NEW);c.execute(()->{pending=false;var item=new JsonObject();item.addProperty("case",caseIndex);item.add("apply",new Gson().toJsonTree(apply.result().getNow(null)));item.add("undo",new Gson().toJsonTree(result));cases.add(item);if(++caseIndex<3)stage=2;else stage=15;});}catch(Exception e){c.execute(()->fail(c,e));}});return;}
        if(stage==15){pending=true;var server=c.getServer();server.execute(()->{try{if(!server.saveAll(false,true,true))throw new IllegalStateException("Normal fixture save not acknowledged");c.execute(()->{try{report.add("cases",cases);report.addProperty("result","passed");report.addProperty("newWorldCreated",true);report.addProperty("formalWorldOpened",false);report.addProperty("modelCalls",0);report.addProperty("fixtureProposalOnly",true);report.addProperty("savedAcknowledged",true);report.addProperty("worldDurabilityVerified",false);report.addProperty("seconds",(System.nanoTime()-started)/1e9);Files.writeString(output.resolve("report.json"),new GsonBuilder().setPrettyPrinting().create().toJson(report),StandardOpenOption.CREATE_NEW);stage=99;c.scheduleStop();}catch(Exception e){fail(c,e);}});}catch(Exception e){c.execute(()->fail(c,e));}});}
    }catch(Exception e){fail(c,e);}}
    private static void openPlacement(MinecraftClient c){c.setScreen(new WorldPatchPlacementScreen(new SelectionScreen(new TitleScreen()),candidate));pending=true;var server=c.getServer();var user=c.player.getUuid();server.execute(()->{try{observed=dev.voxelstudio.WorldChangeTracker.watch(server.getPlayerManager().getPlayer(user).getServerWorld(),capture.selection().context());preparationRevision=observed.revision();c.execute(()->{pending=false;stage=5;});}catch(Exception e){c.execute(()->fail(c,e));}});}
    private static boolean active(MinecraftClient c,String prefix){return c.currentScreen!=null&&c.currentScreen.children().stream().anyMatch(v->v instanceof ClickableWidget w&&w.visible&&w.active&&w.getMessage().getString().startsWith(prefix));}
    private static void press(MinecraftClient c,String prefix){if(c.currentScreen==null)throw new IllegalStateException("Missing UI for "+prefix);var screen=c.currentScreen;var button=screen.children().stream().filter(v->v instanceof ClickableWidget w&&w.visible&&w.active&&w.getMessage().getString().startsWith(prefix)).map(v->(ClickableWidget)v).findFirst().orElseThrow(()->new IllegalStateException("Missing active button "+prefix));double x=button.getX()+button.getWidth()/2.0,y=button.getY()+button.getHeight()/2.0;if(!screen.mouseClicked(x,y,0))throw new IllegalStateException("Button event unhandled");screen.mouseReleased(x,y,0);}
    private static void screenshot(MinecraftClient c,String name)throws Exception{try(var image=net.minecraft.client.util.ScreenshotRecorder.takeScreenshot(c.getFramebuffer())){image.writeTo(output.resolve(name));}}
    private static void fail(MinecraftClient c,Throwable e){try{if(observed!=null)observed.close();var f=new JsonObject();f.addProperty("result","failed");f.addProperty("stage",stage);f.addProperty("case",caseIndex);f.addProperty("error",String.valueOf(e));f.addProperty("worldDurabilityVerified",false);if(output!=null)Files.writeString(output.resolve("failure.json"),f.toString(),StandardOpenOption.CREATE_NEW);}catch(Exception ignored){}stage=99;c.scheduleStop();}
    private WorldPatchTransactionSelfTest(){}
}
