import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import path from 'node:path';import os from 'node:os';import {deflateSync} from 'node:zlib';import {setTimeout as delay} from 'node:timers/promises';
import {reviewPngs} from '../../bridge/visual-review.mjs';import {generationPreflight} from '../../bridge/generation-policy.mjs';import {startBridge} from '../../bridge/server.mjs';import {sampleSpec} from '../../src/generation/sample.mjs';import {CodexAdapter} from '../../bridge/codex-adapter.mjs';
function crc(b){let c=0xffffffff;for(const x of b){c^=x;for(let i=0;i<8;i++)c=c&1?0xedb88320^(c>>>1):c>>>1;}return (c^0xffffffff)>>>0;}
function png(){const chunk=(type,b)=>{const t=Buffer.from(type),head=Buffer.alloc(4),end=Buffer.alloc(4);head.writeUInt32BE(b.length);end.writeUInt32BE(crc(Buffer.concat([t,b])));return Buffer.concat([head,t,b,end]);};const header=Buffer.alloc(13);header.writeUInt32BE(512);header.writeUInt32BE(512,4);header[8]=8;header[9]=6;return Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]),chunk('IHDR',header),chunk('IDAT',deflateSync(Buffer.alloc(512*(512*4+1)))),chunk('IEND',Buffer.alloc(0))]).toString('base64');}
test('visual review accepts four bounded PNGs, rejects paths and non-image agents',()=>{assert.equal(reviewPngs(Array(4).fill(png())).length,4);for(const images of [[],['C:/private.png'],Array(4).fill('not-png')])assert.throws(()=>reviewPngs(images));for(const agent of ['claude','deepseek'])assert.throws(()=>generationPreflight({agent,baseJobId:'x',baseHash:'x',prompt:'refine',reviewImages:Array(4).fill(png())}));assert.throws(()=>generationPreflight({agent:'codex',baseJobId:'x',baseHash:'x',prompt:'refine',maxRepairs:1,reviewImages:Array(4).fill(png())}));});
test('explicit one-call image refinement preserves original asset and never retries',async()=>{
 const dataDir=await fs.mkdtemp(path.join(os.tmpdir(),'voxel-visual-'));let calls=0;const adapter={close(){},async models(){return [{id:'vision-fixture',supportsImages:true}]},async generate({prompt,images,cwd}){calls++;assert.match(prompt,/VISUAL REFINEMENT/);assert.equal(images.length,4);for(const file of images){assert.equal(path.dirname(file),cwd);assert.ok((await fs.stat(file)).size>0);}return {spec:sampleSpec()};}};
 const b=await startBridge({dataDir,adapter}),base=`http://127.0.0.1:${b.connection.port}`,headers={Authorization:`Bearer ${b.connection.token}`,'Content-Type':'application/json'};
 const post=async input=>{const r=await fetch(base+'/v1/jobs',{method:'POST',headers,body:JSON.stringify(input)});assert.ok(r.ok,await r.clone().text());return r.json();};const wait=async id=>{for(let i=0;i<150;i++){const j=await(await fetch(base+'/v1/jobs/'+id,{headers})).json();if(['failed','preview-ready'].includes(j.state))return j;await delay(20);}throw new Error('Timeout');};
 try{const original=await wait((await post({key:'original',sample:true})).id),saved=await fs.readFile(path.join(dataDir,'jobs',original.id,'job.json'));const request={key:'visual-one',agent:'codex',model:'vision-fixture',prompt:'improve window depth',baseJobId:original.id,baseHash:original.assetHash,reviewImages:Array(4).fill(png()),maxRepairs:0};const result=await wait((await post(request)).id);assert.equal(result.state,'preview-ready',result.error);assert.equal(result.visualReview.views,4);assert.equal(calls,1);await post(request);assert.equal(calls,1);assert.deepEqual(await fs.readFile(path.join(dataDir,'jobs',original.id,'job.json')),saved);const denied=await wait((await post({...request,key:'no-image',model:'text-only'})).id);assert.equal(denied.state,'failed');assert.equal(calls,1);}finally{await b.close();}
});
test('Codex image capability comes from catalog, unknown capability is conservative',async()=>{const a=new CodexAdapter();a.connect=async()=>{};a.request=async()=>({data:[{model:'vision',inputModalities:['text','image']},{model:'unknown'}]});const models=await a.models();assert.equal(models[0].supportsImages,true);assert.equal(models[1].supportsImages,false);});
test('corrupt PNG checksums and header/pixel channel mismatches are rejected',()=>{let b=Buffer.from(png(),'base64');b[40]^=1;assert.throws(()=>reviewPngs(Array(4).fill(b.toString('base64'))),/checksum/);b=Buffer.from(png(),'base64');b[25]=2;b.writeUInt32BE(crc(b.subarray(12,29)),29);assert.throws(()=>reviewPngs(Array(4).fill(b.toString('base64'))),/pixel length/);});
