package dev.voxelstudio.client;
import com.google.gson.JsonObject;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import java.io.IOException;
import java.nio.file.*;
import java.util.*;
import static org.junit.jupiter.api.Assertions.*;
final class WorldPatchReferencesTest {
    @TempDir Path temp;
    private JsonObject reference()throws Exception{var f=WorldPatchTaskReceiptTest.fixture();return WorldPatchJobReceipt.reference(ContextTaskReceiptTest.capture(f),f.getAsJsonObject("prepared"),f.getAsJsonObject("frozen"),f.get("runtimeHash").getAsString());}
    private Path file(Path root,JsonObject r){return root.resolve("world-patch-references").resolve(r.get("capsuleId").getAsString()+".json");}
    @Test void durableClaimSurvivesRestartAndNeverRebindsBaseline()throws Exception{var root=temp.resolve("data");var store=new WorldPatchReferences(root);var r=reference();assertEquals(List.of(),store.list());assertTrue(store.claim(r));assertFalse(store.claim(r));assertFalse(new WorldPatchReferences(root).claim(r));assertEquals(List.of(r),store.list());assertEquals(r,store.read(r.get("capsuleId").getAsString()));var changed=r.deepCopy();changed.addProperty("snapshotHash","a".repeat(64));assertThrows(IOException.class,()->store.claim(changed));assertEquals(r,store.read(r.get("capsuleId").getAsString()));}
    @Test void noPermissionAndNoAdoptionOfMutatedCopies()throws Exception{var store=new WorldPatchReferences(temp.resolve("data"));var r=reference();store.remember(r);var copy=store.list().get(0);copy.addProperty("canAuthorizePlacement",true);assertFalse(store.list().get(0).get("canAuthorizePlacement").getAsBoolean());assertThrows(RuntimeException.class,()->store.remember(copy));}
    @Test void corruptRecordIsRetainedNotRegenerated()throws Exception{var root=temp.resolve("data");var store=new WorldPatchReferences(root);var r=reference();store.remember(r);Files.writeString(file(root,r),"tampered");assertThrows(IOException.class,store::list);assertThrows(IOException.class,()->store.claim(r));assertEquals("tampered",Files.readString(file(root,r)));}
    @Test void completeButUnpublishedPendingCannotBecomeHistoryOrConsent()throws Exception{var root=temp.resolve("data");var store=new WorldPatchReferences(root);var r=reference();store.remember(r);Path pending=root.resolve("world-patch-references/.pending-"+UUID.randomUUID()+".json");Files.copy(file(root,r),pending);assertEquals(List.of(r),store.list());assertFalse(store.claim(r));assertTrue(Files.exists(pending));assertArrayEquals(Files.readAllBytes(file(root,r)),Files.readAllBytes(pending));}
    @Test void unpublishedLegacyPendingIsPreservedWithoutNewDispatchClaim()throws Exception{var root=temp.resolve("data");var store=new WorldPatchReferences(root);var r=reference();store.remember(r);Path pending=root.resolve("world-patch-references/.pending-"+UUID.randomUUID()+".json");Files.move(file(root,r),pending);var bytes=Files.readAllBytes(pending);assertEquals(List.of(),store.list());assertThrows(IOException.class,()->store.claim(r));assertArrayEquals(bytes,Files.readAllBytes(pending));assertFalse(Files.exists(file(root,r)));}
    @Test void quotaPreservesEveryOriginalAndDoesNotEvictPending()throws Exception{var root=temp.resolve("data");var store=new WorldPatchReferences(root);var original=reference();for(int i=1;i<=7;i++){var r=original.deepCopy();String id=String.format("%064x",i);r.addProperty("capsuleId",id);r.getAsJsonObject("send").addProperty("capsuleId",id);r.addProperty("submissionHash",ContextReceipt.jsonHash(r.get("send")));store.remember(r);}Path pending=root.resolve("world-patch-references/.pending-"+UUID.randomUUID()+".json");Files.writeString(pending,"incomplete-preserved");assertEquals(7,store.list().size());assertThrows(IOException.class,()->store.claim(original));assertEquals("incomplete-preserved",Files.readString(pending));assertEquals(7,store.list().size());}
    @Test void malformedUtf8AndDuplicateFieldsAreNotParsedAsValidHistory()throws Exception{var root=temp.resolve("data");var store=new WorldPatchReferences(root);var r=reference();store.remember(r);Path target=file(root,r);String original=Files.readString(target);Files.writeString(target,original.replaceFirst("\\{","{\"format\":\"SavedWorldPatchReference\","));assertThrows(IOException.class,store::list);Files.write(target,new byte[]{(byte)0xc0,(byte)0x80});assertThrows(IOException.class,()->store.claim(r));assertArrayEquals(new byte[]{(byte)0xc0,(byte)0x80},Files.readAllBytes(target));}
    @Test void traversalForeignFilesAndWrongRootTypesCannotAuthorizeAnything()throws Exception{var root=temp.resolve("data");var store=new WorldPatchReferences(root);assertThrows(IllegalArgumentException.class,()->store.read("../private"));Files.createDirectories(root);Files.writeString(root.resolve("world-patch-references"),"preserve");assertThrows(IOException.class,()->store.claim(reference()));assertEquals("preserve",Files.readString(root.resolve("world-patch-references")));var other=new WorldPatchReferences(temp.resolve("other"));other.remember(reference());Path foreign=temp.resolve("other/world-patch-references/private-file");Files.writeString(foreign,"preserve-foreign");assertThrows(IOException.class,other::list);assertEquals("preserve-foreign",Files.readString(foreign));}
}
